### ISSUE TITLE
Start testing Nim compiler version 1.6 on testnet nodes

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#103]
Since `nimbus-eth2` is supposed to upgrade it's Nim compiler from `1.2` to `1.6` we'll need to adjust building process of some of the nodes to start using Nim `1.6`. In order to do that we can use the `NIM_COMMIT` variable:
```sh
make V=1 NIM_COMMIT='version-1-6'
```
It should be also possible to target specific release versions:
```sh
make V=1 NIM_COMMIT='v1.6.6'
```
These changes should be gradually rolled out to more and more testnet(Prater, Ropsten, and Kiln) nodes:

>Probably start at some minority (10% maybe or some convenient number in that range, no more than 25% at least) on 1.6, with the goal of increasing it gradually.
>-- @tersec

This should be configurable through the `nodes_layout` list so we can select which nodes will be using new Nim version.
This can be achieved using the [`beacon_node_nim_commit` variable](https://github.com/status-im/infra-role-beacon-node-linux/blob/a573ab89f2a75a7c80ba98e254b26644b9eb2fb2/defaults/main.yml#L100-L102).

No clear deadline is given, Nim upgrade is planned sometime in the next couple of months.

**Comment by Menduist** [comment]
Note: some servers are already running 1.6,but they're misconfigured:
https://github.com/status-im/infra-nimbus/blob/master/ansible/group_vars/nimbus.prater.yml#L96
They're shouldn't point to the nim 1.6 branch at this point

**Comment by Marudny** [comment]
https://github.com/status-im/infra-nimbus/pull/112

Changes have been deployed to the `metal-05.he-eu-hel1.nimbus.prater` host. Building is in progress.

**Comment by zah** [comment]
This has been delivered
