### ISSUE TITLE
Don't restart Nimbus instances when they fail with due to detected doppelgangers

### ISSUE THREAD

**Issue by zah** [status-im/infra-nimbus#105]
All Nimbus roles can be tweaked to avoid restarting the created system services when the Nimbus beacon node process exits with the value `1031`. See the following issue for the rationale for this:

https://github.com/status-im/nimbus-eth2/issues/3687

**Comment by jakubgs** [comment]
This has already been added and deployed: https://github.com/status-im/infra-role-beacon-node-linux/commit/a7c7a486
