### ISSUE TITLE
Fix Ropsten Geth node and validator layout

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#117]
When we initially deployed Geth for Ropsten testnet merge we made a mistake of deploying just one for 4 beacon nodes:
https://github.com/status-im/infra-nimbus/blob/57ec2fd903a18866078964bb1de70830c75dc98e/ansible/group_vars/nimbus.ropsten.yml#L25-L31
To fix that we'll need to:

1. Deploy 3 more Geth nodes to match the other 3 Beacon nodes ([like in Sepolia](https://github.com/status-im/infra-nimbus/blob/master/ansible/vars/nimbus-sepolia-metal.yml)).
2. Let the Geth nodes sync, possibly help it by copying data from already synced Geth node(when stopped of course).
3. Connect the other 3 Beacon nodes to the new Geth nodes and verify they communicate.
4. Change the validators layout so each node has 2500 validators.

**Comment by jakubgs** [comment]
I didn't clarify the fate of the current `ropsten-01.aws-eu-central-1a.nimbus.geth` host properly.

Since a Geth snap sync of Ropsten is ~160 GB:
```
admin@ropsten-01.aws-eu-central-1a.nimbus.geth:~ % sudo du -hsc /data/nimbus-ropsten
154G	/data/nimbus-ropsten
154G	total
```
It will make more sense to deploy these 4 nodes on our Hetzner host. But for that to make sense we'll need an extra 1TB NVMe:
https://www.hetzner.com/additional-hardware/

No RAID1 necessary as this is just a testnet.

**Comment by Marudny** [comment]
Additional disk has been installed.
4 geth instances have been deployed and syncing. I'm going to give them time till tomorrow morning. Hopefully it will sync. Existing beacon node instance and geth instance haven't been touched yet.

**Comment by jakubgs** [comment]
You forgot to add a reference to the issue in the PR/commit. I added it to the PR.

Also, are you not going to commit the Geth node configuration?
If you are doing this in stages it makes sense to commit each one.

**Comment by jakubgs** [comment]
Looks like it's reasonably fast:
```
admin@metal-01.he-eu-hel1.nimbus.ropsten:~ % for nodeDir in /docker/nimbus-ropsten-*;do $nodeDir/rpc.sh eth_syncing | jq -c '.result | { currentBlock, highestBlock }'; done
{"currentBlock":"0xbc7498","highestBlock":"0xc0b000"}
{"currentBlock":"0xbc74c5","highestBlock":"0xc0aca8"}
{"currentBlock":"0xbc74b7","highestBlock":"0xbda259"}
{"currentBlock":"0xbc7451","highestBlock":"0xc0ac0b"}

admin@metal-01.he-eu-hel1.nimbus.ropsten:~ % sudo du -hsc /docker/nimbus-ropsten-*                                                                                          
135G	/docker/nimbus-ropsten-01
134G	/docker/nimbus-ropsten-02
135G	/docker/nimbus-ropsten-03
132G	/docker/nimbus-ropsten-04
535G	total
```

**Comment by Marudny** [comment]
> You forgot to add a reference to the issue in the PR/commit. I added it to the PR.
> 
> Also, are you not going to commit the Geth node configuration? If you are doing this in stages it makes sense to commit each one.

Yeah, I'm making that in stages. Have created PR with WIP annotation.

Regarding speed - it was quite fast during the night. Now it's stuck on 98 - 99%.

**Comment by Marudny** [comment]
Current state:
```
artur@metal-01.he-eu-hel1.nimbus.ropsten:/var/log/docker % for nodeDir in /docker/nimbus-ropsten-*;do $nodeDir/rpc.sh eth_syncing | jq -c '.result | { currentBlock, highestBlock }'; done
{"currentBlock":"0xbc7498","highestBlock":"0xbdb128"}
{"currentBlock":"0xbc74c5","highestBlock":"0xbdb12a"}
{"currentBlock":"0xbc74b7","highestBlock":"0xbdb12b"}
jq: error (at <stdin>:5): Cannot index boolean with string "currentBlock"
```

`Nodes 01-03` are still in sync state. All three are in `State heal` phase which is extremely slow. Ex. https://github.com/ethereum/go-ethereum/issues/23191

I've copied `chaindata` from `AWS ropsten` node to `node 04`. Unfortunately node is not in sync phase, because of very small number of peers supporting snap.
```artur@metal-01.he-eu-hel1.nimbus.ropsten:/var/log/docker % for nodeDir in /docker/nimbus-ropsten-04;do $nodeDir/rpc.sh admin_peers | jq '.result| length'; done                                
21```

```artur@metal-01.he-eu-hel1.nimbus.ropsten:/var/log/docker % for nodeDir in /docker/nimbus-ropsten-04;do $nodeDir/rpc.sh admin_peers | jq '.result[].caps' | grep "snap/1" | wc -l; done
14
```
21 peers in total, only 14 supporting snaps.

**Comment by jakubgs** [comment]
Looks like we are finally synced:
```
admin@metal-01.he-eu-hel1.nimbus.ropsten:~ % for dir in /docker/nimbus*;do $dir/rpc.sh eth_syncing | jq -c; done    
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
{"jsonrpc":"2.0","id":1,"result":false}
```

**Comment by jakubgs** [comment]
I've updated the nodes to use local Geth instances and spread out the validators between all four nodes:

- https://github.com/status-im/infra-nimbus/commit/b4b97d93 - nimbus.ropsten: spread validators between all nodes

https://github.com/status-im/infra-nimbus/blob/b4b97d93388289fd000e74675698415c772c4c7f/ansible/group_vars/nimbus.ropsten.yml#L62-L67

**Comment by jakubgs** [comment]
Looks like everything is working fine on all four nodes:

![image](https://user-images.githubusercontent.com/2212681/183721596-1a19635e-4a32-4e45-abf9-7a127a916f28.png)

![image](https://user-images.githubusercontent.com/2212681/183721665-cc1290ba-c415-4df7-910a-c5a3ef189e06.png)

![image](https://user-images.githubusercontent.com/2212681/183721738-99aa3bab-1ca6-46f1-8e50-1da5e6b3ca45.png)

![image](https://user-images.githubusercontent.com/2212681/183721794-e266bde6-67f2-4190-a701-8265c81388e3.png)

I consider this done.

**Comment by jakubgs** [comment]
Got rid of the AWS Geth node that's now unused: https://github.com/status-im/infra-nimbus/commit/7d0029b9
