### ISSUE TITLE
Run MEV on some Prater/Goerli nodes

### ISSUE THREAD

**Issue by tersec** [status-im/infra-nimbus#124]
This is going to be the main long-lived, ongoing testnet, since first Kiln then Ropsten are scheduled for deprecation this year.

One or two nodes should be fine, but it'd probably be better for them to be individually not terribly larger, no more than in the low hundreds of validators until https://github.com/status-im/nimbus-eth2/issues/3998 is fixed, at which point it won't matter how many validators are present/active.

**Comment by tersec** [comment]
looks good

**Comment by jakubgs** [comment]
Cool.
