### ISSUE TITLE
Create a nim-waku fleet

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#13]
We need a test fleet for Waku implementation in Nim: https://github.com/status-im/nim-waku

The fleet should be separate from Nimbus test fleet and once tested will probably replace `eth.prod`.

**Comment by jakubgs** [comment]
Apparently `nim-waku` doesn't implement all functionalities provided by `status-go`, for example the history node functionality is not ready.

**Comment by jakubgs** [comment]
Created an infrastructure repository for Nim Waku fleet: https://github.com/status-im/infra-nim-waku

**Comment by jakubgs** [comment]
I've prepared a PR with a `Dockerfile` for `nim-waku`: https://github.com/status-im/nim-waku/pull/17

**Comment by jakubgs** [comment]
Deployed 3 hosts 3 DCs, one in each:
```
 > ansible localhost -m debug -a 'var=groups["all"]'
localhost | SUCCESS => {
    "groups[\"all\"]": [
        "node-01.ac-cn-hongkong-c.waku.test",
        "node-01.do-ams3.waku.test",
        "node-01.gc-us-central1-a.waku.test"
    ]
}
```
Next step is to get nodes going, I'll do that tomorrow.

**Comment by jakubgs** [comment]
I implemented a `nim-waku` Ansible role: https://github.com/status-im/infra-nim-waku/commit/51c8671e

**Comment by jakubgs** [comment]
Waku nodes are up:

* https://consul.status.im/ui/do-ams3/nodes/node-01.do-ams3.waku.test
* https://consul.status.im/ui/gc-us-central1-a/nodes/node-01.gc-us-central1-a.waku.test
* https://consul.status.im/ui/ac-cn-hongkong-c/nodes/node-01.ac-cn-hongkong-c.waku.test

One `nim-waku-node` container on each host.

**Comment by jakubgs** [comment]
Currently the following flags are necessary to build an image for the fleet:
```
make docker-image DOCKER_IMAGE_NIM_PARAMS="-d:chronicles_colors:none -d:insecure"
```

**Comment by jakubgs** [comment]
Deployed metrics to Prometheus: https://github.com/status-im/infra-hq/commit/e1c83dd9
And started creating a dashboard here: https://grafana.status.im/d/yy23i_zGk/nim-waku
But I noticed that dropped envelope metrics have bad format: https://github.com/status-im/nim-waku/issues/24

**Comment by jakubgs** [comment]
I have created a Scaleway module for Terraform in https://github.com/status-im/infra-ci/commit/853c1bc6 and I tried creating an instance of type `GP-BM1-S` but that did not work:
```
Error: scaleway-sdk-go:
  invalid argument(s): commercial_type does not respect constraint, Invalid commercial type "GP-BM1-S".
  Available types: [C1, C2S, C2M, C2L, VC1S, VC1M, VC1L, START1-XS, START1-S, START1-M, START1-L, X64-15GB, X64-30GB, X64-60GB, X64-120GB, ARM64-2GB, ARM64-4GB, ARM64-8GB, ARM64-16GB, ARM64-32GB, ARM64-64GB, ARM64-128GB, RENDER-S, GP1-XS, GP1-S, GP1-M, GP1-L, GP1-XL, DEV1-S, DEV1-M, DEV1-L, DEV1-XL]
```
It might be that Scaleway doesn't support creating them with Terraform currently.

**Comment by jakubgs** [comment]
I opened a ticket with Scaleway support:
```
Hey,

I was trying to create a Bare Metal instance using Terraform but when I tried making a `C2S` I got back:
Error: scaleway-sdk-go: quota exceeded(s): servers_type_C2S has reached its quota (0/0)

So I tried to create a GP-BM1-S but I can't seem to be able to find the right name for the instance:
Error: scaleway-sdk-go: invalid argument(s): commercial_type does not respect constraint, Invalid commercial type "GP-BM1-S"

And your CLI tool when calling `scw products servers` doesn't return anything similar to `GP-BM1-S`.

How can I create it?
```
https://console.scaleway.com/support/tickets/PNFR-7250-JYII

**Comment by jakubgs** [comment]
Thanks to @kdeme we now have nice metrics for dropped envelopes:
```
admin@node-01.do-ams3.waku.test:~ % curl -s localhost:8008/metrics | grep '^envelopes_dropped'
envelopes_dropped_total{reason="duplicate"} 8446.0
envelopes_dropped_created{reason="duplicate"} 1591705726.0
envelopes_dropped_total{reason="benign_duplicate"} 743.0
envelopes_dropped_created{reason="benign_duplicate"} 1591706036.0
envelopes_dropped_total{reason="expired"} 651.0
envelopes_dropped_created{reason="expired"} 1591706037.0
```

**Comment by jakubgs** [comment]
I've adjusted the metrics dashboard to use the new metrics:
https://grafana.status.im/d/yy23i_zGk/nim-waku?orgId=1&refresh=5m&from=now-1h&to=now
Looks nice.

**Comment by jakubgs** [comment]
One more thing I'd like to have is an RPC healthcheck using `admin_nodeInfo`.

**Comment by oskarth** [comment]
@jakubgs would it be possible to get the existing Waku v2 nodes (one at the moment!) to show up in https://fleets.status.im/? It can be a separate fleet or part of one of the existing test ones. Whatever is easiest.

cc @bgits @kdeme

**Comment by jakubgs** [comment]
@oskarth Okay, but have you implemented the `admin_nodeInfo` call I requested in https://github.com/status-im/nim-waku/issues/28, and if not how can I get the enode in a reliable way?

**Comment by oskarth** [comment]
Ah right. That's for v1 though. We can add something minimal for v2 to get the the nodeid (similar conceptually but not identical to enode). Created issue here: https://github.com/status-im/nim-waku/issues/201

**Comment by jakubgs** [comment]
Do you need it to be available under main `fleets.status.im` JSON or would you be fine with a separate file?
The script that generates that was not written with other fleets in mind.

**Comment by jakubgs** [comment]
BTW, I adjusted service names to distinguish between v1 and v2: https://github.com/status-im/infra-nim-waku/commit/327639ec

**Comment by jakubgs** [comment]
Okay, I modified the script, it wasn't that complicated: https://github.com/status-im/infra-eth-cluster/commit/b57f9f0a
```
 > curl -sL fleets.status.im | jq '.fleets["wakuv2.test"]' 
{
  "waku": {
    "node-01.do-ams3.wakuv2.test": "/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"
  }
}
```
