### ISSUE TITLE
Return of ElasticSearch cluster "Data too large" errors

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#138]
We've had this issue before:

* https://github.com/status-im/infra-nimbus/issues/96

And we resolved it by adjusting the size of the heap, which helped for a while: https://github.com/status-im/infra-nimbus/commit/c474a3311d6653c2d8becdca084ae95b5a6f6fce

https://github.com/status-im/infra-nimbus/blob/c474a3311d6653c2d8becdca084ae95b5a6f6fce/ansible/group_vars/logs.nimbus.yml#L39-L41

But it's back again:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_cat/indices\?s=index\&v | jq
curl: (22) The requested URL returned error: 429
```
```json
{
  "error": {
    "root_cause": [
      {
        "type": "circuit_breaking_exception",
        "reason": "[parent] Data too large, data for [<http_request>] would be [31532379056/29.3gb], which is larger than the limit of [31282010521/29.1gb], real usage: [31532379056/29.3gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, eql_sequence=0/0b, accounting=28007664/26.7mb]",
        "bytes_wanted": 31532379056,
        "bytes_limit": 31282010521,
        "durability": "PERMANENT"
      }
    ],
    "type": "circuit_breaking_exception",
    "reason": "[parent] Data too large, data for [<http_request>] would be [31532379056/29.3gb], which is larger than the limit of [31282010521/29.1gb], real usage: [31532379056/29.3gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, eql_sequence=0/0b, accounting=28007664/26.7mb]",
    "bytes_wanted": 31532379056,
    "bytes_limit": 31282010521,
    "durability": "PERMANENT"
  },
  "status": 429
}
```

**Comment by jakubgs** [comment]
The cluster stopped handling requests sometimes around 8:30pm yesterday:

![image](https://user-images.githubusercontent.com/2212681/213420667-de20035e-6bf3-4855-844b-54950a6a7d98.png)

Cirtcuit breakers started firing:

![image](https://user-images.githubusercontent.com/2212681/213420794-307df497-0caa-45bd-8353-a7541576b8a5.png)

**Comment by jakubgs** [comment]
JVM buffer size reached 32.2 GB:

![image](https://user-images.githubusercontent.com/2212681/213421147-e54adabe-296c-4b49-ab75-d582b42f7daa.png)

If we look at memory on `store-01.he-eu-hel1.logs.nimbus` it started struggling on the 14th already:

![image](https://user-images.githubusercontent.com/2212681/213421865-36ba0527-4257-4851-b08a-c8bab448b97f.png)

**Comment by jakubgs** [comment]
I'm sure there's some tuning we could do, but for now I think the reasonable thing is to just get bigger hosts.

And there's a sale on AX101, you can get them without the setup fee:

![image](https://user-images.githubusercontent.com/2212681/213422932-0c31b9d5-a722-4ce6-b090-c7ce10cf914d.png)

https://www.hetzner.com/dedicated-rootserver/matrix-ax

**Comment by jakubgs** [comment]
The new hosts will cost 352 EUR per month, no setup fee:

![image](https://user-images.githubusercontent.com/2212681/213424975-e08c6322-68a2-47e0-a4f8-079fa4a301c9.png)

Minus the ~135 EUR we currently pay for 3x AX41-NVMe that's an increase of 217 EUR.

I will reuse one or two hosts for CI, the rest will be decomissioned.

**Comment by jakubgs** [comment]
I've added the new hosts to repo and bootstrapped them:

- https://github.com/status-im/infra-nimbus/commit/ec6e8c47 - replace logs.nimbus hosts with new AX101 servers

https://github.com/status-im/infra-nimbus/blob/ec6e8c47ba5a0623b8f6cc1de002def92b393865/ansible/inventory/test#L30-L32

**Comment by jakubgs** [comment]
I've deployed ElasticSearch cluster on the new nodes:

- https://github.com/status-im/infra-nimbus/commit/9f0ab35e - requirements: bump elasticsearch and kiban to 7.17.8
- https://github.com/status-im/infra-nimbus/commit/e73125a2 - replace logs.nimbus hosts with new AX101 servers
- https://github.com/status-im/infra-nimbus/commit/ee1ed520 - logs/dash.nimbus: drop manual JVM heap size setting

Unfortunately I didn't back up the Kibana config, but I've re-created the main dashboard.
https://nimbus-logs.infra.status.im/app/dashboards#/view/fcd4bb70-9802-11ed-a7ee-a9d9f8b0eec3

**Comment by jakubgs** [comment]
Looks like the issue is back:

![image](https://user-images.githubusercontent.com/2212681/215267479-5057692e-a1e7-4d90-8792-74ac6e254b86.png)

The `parent` circuit breakers started triggering around that time:

![image](https://user-images.githubusercontent.com/2212681/215267558-be2588b8-b3d6-4704-8650-8925c84ada68.png)

But the memory usage isn't actually high:

![image](https://user-images.githubusercontent.com/2212681/215267723-d66fa331-cb4c-4803-93d7-d7174da7f901.png)

So this is a matter of tuning settings.

**Comment by jakubgs** [comment]
Looks like the automatic heap mas size is 29.7 GB:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_cat/nodes\?h=heap\*\&v
heap.current heap.percent heap.max
         4gb           13   29.7gb
       8.4gb           27   29.7gb
       6.4gb           21   29.7gb
     201.9mb           10    1.8gb
```
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_nodes/stats | jq '.nodes[].jvm.mem.heap_committed_in_bytes'                 
31899254784
33065795584
31899254784
2031091712
```
I've increased it manually to 48 GB:

- https://github.com/status-im/infra-nimbus/commit/61d586fa - logs.nimbus: set static max heap size to 48 GB

Lets see how well that works. All docs and forums say to keep it under 50% of available memory, which in this case is 64 GB.

**Comment by jakubgs** [comment]
While debugging I identified a pretty weird networking issue on some of the hosts:
```
admin@store-02.he-eu-hel1.logs.nimbus:~ % sudo nmap -Pn -p9200 127.0.0.1          
Nmap scan report for localhost.localdomain (127.0.0.1)
Host is up.

PORT     STATE    SERVICE
9200/tcp filtered wap-wsp

Nmap done: 1 IP address (1 host up) scanned in 2.08 seconds

admin@store-02.he-eu-hel1.logs.nimbus:~ % sudo nmap -Pn -p9200 localhost
Nmap scan report for localhost (127.0.0.1)
Host is up.
rDNS record for 127.0.0.1: localhost.localdomain

PORT     STATE    SERVICE
9200/tcp filtered wap-wsp

Nmap done: 1 IP address (1 host up) scanned in 2.07 seconds

admin@store-02.he-eu-hel1.logs.nimbus:~ % sudo nmap -Pn -p9200 0        
Nmap scan report for 0 (0.0.0.0)
Host is up (0.000029s latency).

PORT     STATE SERVICE
9200/tcp open  wap-wsp

Nmap done: 1 IP address (1 host up) scanned in 0.09 seconds
```
That's just weird.

**Comment by jakubgs** [comment]
This is caused by duplicate entries in `POSTROUTING` chain in the `nat` table:
```
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  anywhere             anywhere             ADDRTYPE match src-type LOCAL
MASQUERADE  all  --  172.17.0.0/24        anywhere            
MASQUERADE  all  --  anywhere             anywhere             ADDRTYPE match src-type LOCAL
MASQUERADE  all  --  172.17.1.0/24        anywhere            
MASQUERADE  tcp  --  172.17.1.2           172.17.1.2           tcp dpt:9300
MASQUERADE  tcp  --  172.17.1.2           172.17.1.2           tcp dpt:9200
MASQUERADE  tcp  --  172.17.1.3           172.17.1.3           tcp dpt:9114
MASQUERADE  tcp  --  172.17.1.3           172.17.1.3           tcp dpt:9300
MASQUERADE  tcp  --  172.17.1.3           172.17.1.3           tcp dpt:9200
MASQUERADE  tcp  --  172.17.1.2           172.17.1.2           tcp dpt:9114
```
Shuttingf down the container and then removing the extra `MASQUERADE` rules fixes the issue.

**Comment by jakubgs** [comment]
We were fine for a while, but it's back:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_cat/indices\?s=index |jq                   
curl: (22) The requested URL returned error: 429
{
  "error": {
    "root_cause": [
      {
        "type": "circuit_breaking_exception",
        "reason": "[parent] Data too large, data for [<http_request>] would be [47278984720/44gb], which is larger than the limit of [46922517708/43.6gb], real usage: [47278984720/44gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, eql_sequence=0/0b, accounting=29949224/28.5mb]",
        "bytes_wanted": 47278984720,
        "bytes_limit": 46922517708,
        "durability": "PERMANENT"
      }
    ],
    "type": "circuit_breaking_exception",
    "reason": "[parent] Data too large, data for [<http_request>] would be [47278984720/44gb], which is larger than the limit of [46922517708/43.6gb], real usage: [47278984720/44gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, model_inference=0/0b, eql_sequence=0/0b, accounting=29949224/28.5mb]",
    "bytes_wanted": 47278984720,
    "bytes_limit": 46922517708,
    "durability": "PERMANENT"
  },
  "status": 429
}
```
This issue is driving me insane.

**Comment by jakubgs** [comment]
Looks like it started on the 8th a bit after midnight, but got really bad on the 16th:

![image](https://user-images.githubusercontent.com/2212681/220208058-2a70d3ec-b611-4d5b-a300-de5b24b24e57.png)

We can see the memory usage reached critical mass at the same time as well:

![image](https://user-images.githubusercontent.com/2212681/220208105-af061c79-a7bb-4c90-9a6a-6ce2de7466d6.png)

Seems like it was the cache that ate it all up.

**Comment by jakubgs** [comment]
Some options for research into circuit breakers firing:
https://www.elastic.co/guide/en/elasticsearch/reference/7.14/fix-common-cluster-issues.html#prevent-circuit-breaker-errors

**Comment by jakubgs** [comment]
For now I've lowered heap size:

- https://github.com/status-im/infra-nimbus/commit/77278c2b - logs.nimbus: lower ES JVM heap size to 40 GB

My next idea is to introduce some query limits, but not sure if that's relevant here.

**Comment by jakubgs** [comment]
We can see that cache usage is gradually increasing:

![image](https://user-images.githubusercontent.com/2212681/220880003-90559cca-e4cc-498e-aaf4-832119d1a537.png)

And awe can see that in shared memory usage on all 3 hosts:

![image](https://user-images.githubusercontent.com/2212681/220881269-e4ad52d4-823d-4108-922f-e35abffe1a45.png)

**Comment by jakubgs** [comment]
As a test I attempted to ["Clear the fieldata cache"](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/fix-common-cluster-issues.html#prevent-circuit-breaker-errors):
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c -XPOST 0:9200/_cache/clear\?fielddata=true
{"_shards":{"total":60,"successful":60,"failed":0}}
```
But as far as I can tell that made no difference, which means we don't use field data for text fields.

**Comment by jakubgs** [comment]
According to the doc:

>Every shard uses memory. In most cases, a small set of large shards uses fewer resources than many small shards. For tips on reducing your shard count, see [Size your shards](https://www.elastic.co/guide/en/elasticsearch/reference/7.14/size-your-shards.html).

But we use only 3 shards per index, and we keep only 14 indices at a time:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_cat/indices\?s=index | grep logstash 
green open logstash-2023.02.10             OZkw2Qn_Sgec0D1eIr7VGA 3 0  5464669     0   1.8gb   1.8gb
green open logstash-2023.02.11             U2ntk29ESiK8-PmaXL53BQ 3 0  4315811     0   1.5gb   1.5gb
green open logstash-2023.02.12             OpVT4tt2SMKTpkjLQVk9bQ 3 0  3153316     0   1.1gb   1.1gb
green open logstash-2023.02.13             k4y6LVnxSneIioxUad3jjQ 3 0  2310239     0 869.9mb 869.9mb
green open logstash-2023.02.14             Khw9HessQPaC0ZuSWqudgg 3 0  2184014     0 788.2mb 788.2mb
green open logstash-2023.02.15             jFQ3UML3R6yIeEGjHHVhQw 3 0  1956190     0 703.5mb 703.5mb
green open logstash-2023.02.16             6O8KcWiKQnGAmYNclErEQw 3 0  1645085     0 605.6mb 605.6mb
green open logstash-2023.02.17             K4wTaDzSQPSXzQBlWKd3IQ 3 0  1472330     0 553.3mb 553.3mb
green open logstash-2023.02.18             r5MxB7C6RxGRmDJ7LYX4Yg 3 0  1059587     0 387.1mb 387.1mb
green open logstash-2023.02.19             GCQjyaZYQQ-9E6UUAf5bQg 3 0   374660     0   143mb   143mb
green open logstash-2023.02.20             0jR0DE4mTpygLg2infSKqQ 3 0  5538422     0   2.3gb   2.3gb
green open logstash-2023.02.21             38SHyBb5TI6oXSsVlIS6_w 3 0 76123990     5  29.1gb  29.1gb
green open logstash-2023.02.22             2vU4Lc3wQeumc5fRXMFoFw 3 0 73862935     0  29.5gb  29.5gb
green open logstash-2023.02.23             F_jhvMM7Qdahr8nczV81yw 3 0 34896953     0  14.7gb  14.7gb
```
So that's most probably not it.

**Comment by jakubgs** [comment]
Here we see that the memory actually constantly growing is from `old` pool in `elasticsearch_jvm_memory_pool_used_bytes`:

![image](https://user-images.githubusercontent.com/2212681/220891044-c62dfe58-87cd-4978-a983-7617803d887e.png)

But not sure how we can adjust garbage collection for that yet:
```sh
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_nodes/stats\?filter_path=nodes.\*.jvm.mem.pools.old | jq
```
```json
{
  "nodes": {
    "35aBLdCRTzKjaJ_ktzNSlQ": {
      "jvm": {
        "mem": {
          "pools": {
            "old": {
              "used_in_bytes": 8431090040,
              "max_in_bytes": 28633464832,
              "peak_used_in_bytes": 8431090040,
              "peak_max_in_bytes": 28633464832
            }
          }
        }
      }
    },
    "eOrlyZucR4mgdq5Cv5sfDA": {
      "jvm": {
        "mem": {
          "pools": {
            "old": {
              "used_in_bytes": 8766491144,
              "max_in_bytes": 28633464832,
              "peak_used_in_bytes": 8766491144,
              "peak_max_in_bytes": 28633464832
            }
          }
        }
      }
    },
    "wOEvCQB3SOO0beCMpw0TDg": {
      "jvm": {
        "mem": {
          "pools": {
            "old": {
              "used_in_bytes": 9259473728,
              "max_in_bytes": 28633464832,
              "peak_used_in_bytes": 9259473728,
              "peak_max_in_bytes": 28633464832
            }
          }
        }
      }
    }
  }
}
```

**Comment by jakubgs** [comment]
Some links for Monday:

* https://www.elastic.co/guide/en/elasticsearch/reference/7.17/important-settings.html
* https://www.elastic.co/blog/managing-and-troubleshooting-elasticsearch-memory
* https://www.elastic.co/guide/en/elasticsearch/reference/7.14/fix-common-cluster-issues.html#high-jvm-memory-pressure
* https://www.elastic.co/guide/en/cloud/current/ec-memory-pressure.html
* https://mincong.io/2020/08/30/gc-in-elasticsearch/

**Comment by jakubgs** [comment]
Looks like cache usage growth has calmed down:

![image](https://user-images.githubusercontent.com/2212681/222145519-ee1b7052-48ec-42f4-871d-bcc5418cc0d1.png)

No idea why.

**Comment by arnetheduck** [comment]
this might be related to using long time ranges - ie I did some 6-month reviews of the data in grafana the other day

**Comment by jakubgs** [comment]
Looks like the logs nodes are broken again:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % c 0:9200/_cat/indices\?s=index | grep logstash
curl: (22) The requested URL returned error: 429
```
And we can see it in graphs:

![image](https://user-images.githubusercontent.com/2212681/222180800-bdde2be4-e4a9-46a8-b37c-19b768222439.png)

Looks like circuit breakers started firing around 4am yesterday.

**Comment by jakubgs** [comment]
Last log from `store-01.he-eu-hel1.logs.nimbus`:
```
[WARN][org.elasticsearch.cluster.action.shard.ShardStateAction] unexpected failure while sending request [internal:cluster/shard/failure] to [{store-02.he-eu-hel1.logs.nimbus}{eOrlyZucR4mgdq5Cv5sfDA}{55ri2R49Q8Si9-rW5C6B3w}{10.14.0.95}{10.14.0.95:9300}{cdfhilmrstw}{ml.machine_memory=134997725184, ml.max_open_jobs=512, xpack.installed=true, ml.max_jvm_size=41160278016, transform.node=true}] for shard entry [shard id [[.kibana_7.17.8_001][0]], allocation id [X7-p31GuRxesXoRFGHrbcg], primary term [0], message [master {store-02.he-eu-hel1.logs.nimbus}{eOrlyZucR4mgdq5Cv5sfDA}{55ri2R49Q8Si9-rW5C6B3w}{10.14.0.95}{10.14.0.95:9300}{cdfhilmrstw}{ml.machine_memory=134997725184, ml.max_open_jobs=512, xpack.installed=true, ml.max_jvm_size=41160278016, transform.node=true} has not removed previously failed shard. resending shard failure], markAsStale [true]]
org.elasticsearch.transport.RemoteTransportException: [store-02.he-eu-hel1.logs.nimbus][172.17.1.3:9300][internal:cluster/shard/failure]
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [internal:cluster/shard/failure] would be [39422207490/36.7gb], which is larger than the limit of [39102264115/36.4gb], real usage: [39422206704/36.7gb], new bytes reserved: [786/786b], usages [request=16472/16kb, fielddata=0/0b, in_flight_requests=786/786b, model_inference=0/0b, eql_sequence=0/0b, accounting=33513972/31.9mb]
```
This clearly is a matter of tuning ES, since we are definitely not running out of resources here.

**Comment by jakubgs** [comment]
I've applied defaults from the Docker container to our JVM settings:

- https://github.com/status-im/infra-role-elasticsearch/commit/5d239ac6 - update jvm config with defaults from container
- https://github.com/status-im/infra-role-elasticsearch-lb/commit/58c2314a - update jvm config with defaults from container

Will test this out for a while, then I'll try to modify the garbage collection settings here:
```jvm
## G1GC Configuration
# NOTE: G1 GC is only supported on JDK version 10 or later
# to use G1GC, uncomment the next two lines and update the version on the
# following three lines to your version of the JDK
# 10-13:-XX:-UseConcMarkSweepGC
# 10-13:-XX:-UseCMSInitiatingOccupancyOnly
14-:-XX:+UseG1GC
```
https://github.com/status-im/infra-role-elasticsearch/blob/5d239ac67f9b0fb87fc772c42089bf25d5849e7c/templates/config/jvm.options.j2#L45-L51

**Comment by jakubgs** [comment]
These are some interesting docs on ES garbage collection:

* https://sematext.com/blog/garbage-collection-settings-elasticsearch-master-nodes/
* https://medium.com/naukri-engineering/garbage-collection-in-elasticsearch-and-the-g1gc-16b79a447181

**Comment by jakubgs** [comment]
Actually, fuck it, I enabled it today:

- https://github.com/status-im/infra-role-elasticsearch/commit/ada672a3 - add es_jvm_g1gc_enabled to change garbage collector
- https://github.com/status-im/infra-role-elasticsearch-lb/commit/96b9a6c6 - add es_jvm_g1gc_enabled to change garbage collector
- https://github.com/status-im/infra-nimbus/commit/10f3132b - logs.nimbus: use G1 garbage collector

It works:
```
admin@store-01.he-eu-hel1.logs.nimbus:/docker/elasticsearch % grep g1gc /var/log/docker/elasticsearch-node/docker.log
[INFO][org.elasticsearch.node.Node] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -Djava.security.manager=allow, -Xms40g, -Xmx40g, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-10213216185544396047, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=21474836480, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=25, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]
[INFO][org.elasticsearch.transport.NettyAllocator] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=32mb}]
```
Let see what that does in the long run.

**Comment by jakubgs** [comment]
So far JVM memory usage seems more flat:

![image](https://user-images.githubusercontent.com/2212681/222469704-35499b5a-557c-4162-8e5d-6db3706a4588.png)

**Comment by jakubgs** [comment]
Call me crazy, but I think it made a difference:

![image](https://user-images.githubusercontent.com/2212681/223409555-ff98f84c-6daf-4681-9390-e95444b0ccb0.png)

The `old` memory pool is growing much slower:

![image](https://user-images.githubusercontent.com/2212681/223409663-f27eb8d1-db31-4ca5-88f3-2c2feb8ade82.png)

But we'll see in the long term.

**Comment by jakubgs** [comment]
Call me crazy, but I think it's fixed:

![image](https://user-images.githubusercontent.com/2212681/225127686-63e81263-2f43-413a-b092-71a674b726fb.png)

![image](https://user-images.githubusercontent.com/2212681/225127773-2f5788ef-cb9f-4248-b2f3-398a5d4cf54a.png)

I think we can call this a success and close this.
