### ISSUE TITLE
High CPU usage by Geth on all Prater nodes

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#143]
For some reason after midnight today all Geth nodes on Prater started using much more CPU time than before:

![image](https://user-images.githubusercontent.com/2212681/224267126-109bfb23-1c35-4b7e-bb3c-2b97c8067dec.png)

This is present on all Prater hosts - with or without validators - and not on Mainnet or Sepolia.

**Comment by jakubgs** [comment]
All hosts have the same behavior, with our without validators:

#### `linux-01`

![image](https://user-images.githubusercontent.com/2212681/224268512-2e6f668b-68a3-4330-b555-eab133762655.png)

#### `linux-04`

![image](https://user-images.githubusercontent.com/2212681/224268559-3f34e4f8-e78b-4ce0-a235-6ba9d10ec9a5.png)

#### `linux-05`

![image](https://user-images.githubusercontent.com/2212681/224268594-bf268700-479f-4e22-8d1c-709bf012d273.png)

#### `linux-06`

![image](https://user-images.githubusercontent.com/2212681/224268629-655bf47f-6620-4781-8012-89955fb871a7.png)

---
And it appears to start on all host at exactly the same time: 00:20:00 UTC (though we can kinda see it get going earlier)

**Comment by jakubgs** [comment]
The new host from InnovaHosting has the same issue:

#### `linux-01.ih-eu-mda1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/224269185-1ff46440-a2ea-4e25-b13c-da21b51e4c65.png)

And there's also a big jump in traffic:

![image](https://user-images.githubusercontent.com/2212681/224269279-474f25a6-1026-427d-b05d-7c1f2083539d.png)

Which indicates to me that this might be a network-wide event.

**Comment by jakubgs** [comment]
Exactly same thing on all hosts:

![image](https://user-images.githubusercontent.com/2212681/224269610-3d63ff07-2b24-4bc7-941b-3fe84719d6a5.png)

**Comment by jakubgs** [comment]
Geth logs show nothing interesting:
```
admin@linux-01.ih-eu-mda1.nimbus.prater:~ % tail -f /var/log/docker/geth-goerli-03-node/docker.log
INFO [03-10|08:55:51.126] Chain head was updated                   number=8,629,532 hash=8b22bb..f930a9 root=15a78f..477d58 elapsed=2.969294ms
WARN [03-10|08:55:55.425] Snapshot extension registration failed   peer=6ec80bbf err="peer connected on snap without compatible eth support"
INFO [03-10|08:56:01.945] Imported new potential chain segment     number=8,629,533 hash=acc958..8300f8 blocks=1         txs=93         mgas=12.119  elapsed=125.810ms        mgasps=96.328   dirty=802.21MiB
INFO [03-10|08:56:02.199] Chain head was updated                   number=8,629,533 hash=acc958..8300f8 root=da3cc3..8ceea7 elapsed=2.089827ms
INFO [03-10|08:56:12.719] Imported new potential chain segment     number=8,629,534 hash=fa13f2..232d8a blocks=1         txs=51         mgas=10.805  elapsed=98.221ms         mgasps=110.006  dirty=802.18MiB
WARN [03-10|08:56:12.821] Snapshot extension registration failed   peer=bfb23f94 err="peer connected on snap without compatible eth support"
INFO [03-10|08:56:12.964] Chain head was updated                   number=8,629,534 hash=fa13f2..232d8a root=7afd44..c46f9f elapsed=1.778947ms
WARN [03-10|08:56:15.075] Served debug_metrics                     reqid=1                         duration="10.868µs"  err="the method debug_metrics does not exist/is not available"
INFO [03-10|08:56:25.183] Imported new potential chain segment     number=8,629,535 hash=45b122..fbb94e blocks=1         txs=131        mgas=29.909  elapsed=219.058ms        mgasps=136.534  dirty=802.04MiB
INFO [03-10|08:56:25.453] Chain head was updated                   number=8,629,535 hash=45b122..fbb94e root=932e28..885ba8 elapsed=3.658001ms
```
It's just the usual stuff.

**Comment by jakubgs** [comment]
Beacon nodes continue to attest just fine:

#### `linux-04.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/224272216-a5a04647-b2aa-4cfd-a333-27b660109ef0.png)

**Comment by jakubgs** [comment]
But we can see a slight increase in dropped/rejected attestations since midnight:

![image](https://user-images.githubusercontent.com/2212681/224272353-e812ed18-8697-4d2c-9d32-c3b63f668e34.png)

And a clear drop-off in received attestations since 2 hours before midnight:

![image](https://user-images.githubusercontent.com/2212681/224272408-af1cb06d-bf01-49ea-b6f0-673ff836d94d.png)

**Comment by holiman** [comment]
I would suggest trying to take a `debug.stacks()` dump. With a bit of luck it may indicate what is spinning. 
Also, if you have access to the geth metrics, it would be interesting to check the goroutine count (was the cpu increase caused by goroutine leak or just a lot of work, e.g. sustained tx influx ?) . Also per-type traffic counters, but those metrics might only be available if the node is running with `metrics.expensive=true`.  If it does, then we could we exactly what type of `eth` message is the majority of that, e.g. if it is tx relays or something else

**Comment by jakubgs** [comment]
@cheatfate has confirmed that his Geth node on Prater is experiencing the same issue.
Which confirms my suspicion that this is not related to our hosts or our setup only.
It still might be related to the combination of geth and nimbus beacon node though.

**Comment by jakubgs** [comment]
As far as I can tell deploying Geth `1.11.4` has resolved the issue:

![image](https://user-images.githubusercontent.com/2212681/224956988-f21c2510-7614-4908-a908-9418101158bf.png)
