### ISSUE TITLE
Multiple EL nodes for CL nodes on Prater

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#144]
We want to test functionality of driving multiple EL nodes with one CL node on Prater.

For that reason we will start by adding a 5th Geth node on both `linux-05.he-eu-hel1.nimbus.prater` and `linux-06.he-eu-hel1.nimbus.prater`.

**Comment by jakubgs** [comment]
Currently we are low on disk space, so we might have to add another SSD and move Geth nodes to it:
```
admin@linux-05.he-eu-hel1.nimbus.prater:~ % sudo du -hsc /data/* /docker/*
24G	/data/beacon-node-prater-libp2p
24G	/data/beacon-node-prater-stable
24G	/data/beacon-node-prater-testing
24G	/data/beacon-node-prater-unstable
145G	/data/era
228G	/docker/geth-goerli-01
260G	/docker/geth-goerli-02
262G	/docker/geth-goerli-03
262G	/docker/geth-goerli-04
5.1M	/docker/log
1.3T	total

admin@linux-05.he-eu-hel1.nimbus.prater:~ % df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            13G  2.1M   13G   1% /run
/dev/md2        1.8T  1.3T  396G  77% /
tmpfs            63G  264K   63G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/md1        989M  249M  689M  27% /boot
tmpfs            13G     0   13G   0% /run/user/8000
tmpfs            13G     0   13G   0% /run/user/2000
```

**Comment by jakubgs** [comment]
I have ordered an extra 2 TB NVMe SSD for `linux-05` and `linux-06` hosts at € 20.90 each per month.

**Comment by arnetheduck** [comment]
> 5th Geth node 

can we make it a non-geth? ie nethermind or something?

**Comment by jakubgs** [comment]
I've added the new NVMes to the hosts:

- https://github.com/status-im/infra-nimbus/commit/5926a3da - nimbus.prater: add extra data volumes for CL nodes

Not sure if I'll do Erigon nodes today.

**Comment by jakubgs** [comment]
Not sure what I can and cannot prune in Erigon node:
```
--prune value  Choose which ancient data delete from DB:
               h - prune history (ChangeSets, HistoryIndices - used by historical state access, like eth_getStorageAt, eth_getBalanceAt, debug_traceTransaction, trace_block, trace_transaction, etc.)
               r - prune receipts (Receipts, Logs, LogTopicIndex, LogAddressIndex - used by eth_getLogs and similar RPC methods)
               t - prune transaction by it's hash index
               c - prune call traces (used by trace_filter method)
               Does delete data older than 90K blocks, --prune=h is shortcut for: --prune.h.older=90000.
               Similarly, --prune=t is shortcut for: --prune.t.older=90000 and --prune=c is shortcut for: --prune.c.older=90000.
               However, --prune=r means to prune receipts before the Beacon Chain genesis (Consensus Layer might need receipts after that).
               If an item is NOT on the list - means NO pruning for this data.
               Example: --prune=htc (default: "disabled")
```
I'm tempted to just prune everything and see what happens.

**Comment by jakubgs** [comment]
Deployed the nodes:

- https://github.com/status-im/infra-nimbus/commit/4a5b7d71 - nimbus.prater: deploy two Erigon nodes

But getting some weird errors at startup:
```
{"lvl":"info","msg":"Initialising Ethereum protocol","network":5,"t":"2023-03-20T21:32:20.985821911Z"}
{"lvl":"info","msg":"Starting private RPC server","on":"127.0.0.1:9090","t":"2023-03-20T21:32:20.990938488Z"}
{"lvl":"info","msg":"new subscription to logs established","t":"2023-03-20T21:32:20.990966361Z"}
{"err":"\u003cnil\u003e","lvl":"eror","msg":"Etherbase account unavailable locally","t":"2023-03-20T21:32:20.991074195Z"}
{"err":"signer missing: %!w(\u003cnil\u003e)","lvl":"eror","msg":"Erigon startup","t":"2023-03-20T21:32:20.991096186Z"}
signer missing: %!w(<nil>)
```

**Comment by jakubgs** [comment]
According to these issues:

* https://github.com/ledgerwatch/erigon/issues/4026
* https://github.com/ledgerwatch/erigon/issues/2588

I should be using the `--miner.sigfile` flag, but I'm already using `--miner.etherbase`:
```
admin@linux-05.he-eu-hel1.nimbus.prater:/docker/erigon-goerli-03 % grep mine docker-compose.yml                    
      --mine=false
      --miner.etherbase=0x45...
```
Which should be enough according to the readme:

>To enable, add `--mine --miner.etherbase=...` or `--mine --miner.miner.sigkey=...` flags.

But right now mining is disabled so I don't get why it needs that. Looks like a bug.

**Comment by jakubgs** [comment]
The value of the `` flag should probably just be a file with private key in it:
```
   --miner.sigfile value                                    Private key to sign blocks with
```

**Comment by jakubgs** [comment]
I've added support for the flag and provided the private key;s

- https://github.com/status-im/infra-role-erigon/commit/9e738072 - add support for --miner.sigfile flag
- https://github.com/status-im/infra-nimbus/commit/cdf362f2 - nimbus.prater: provide private key for mining

But in logs I'm seeing these:
```json
{"err":"Clique.Seal: unauthorized signer","lvl":"warn","msg":"Block sealing failed","t":"2023-03-21T12:05:48.854050206Z"}
```
Not sure if that's a big problem.

**Comment by jakubgs** [comment]
This error comes from:
```go
	// Bail out if we're unauthorized to sign a block
	snap, err := c.Snapshot(chain, number-1, header.ParentHash, nil)
	if err != nil {
		return err
	}
	if _, authorized := snap.Signers[signer]; !authorized {
		return fmt.Errorf("Clique.Seal: %w", ErrUnauthorizedSigner)
	}
```
https://github.com/ledgerwatch/erigon/blob/4087510c2e364c218d34d85c0b1a3bb60d919a69/consensus/clique/clique.go#L423-L430

This is kinda surprising to me. Normally Geth doesn't need a private key, and I'm not sure if this isn't some leftover from before the merge.

**Comment by jakubgs** [comment]
I have connected the two `unstable` beacon nodes to the Erigon nodes:

- https://github.com/status-im/infra-nimbus/commit/9aa83f8d - nimbus.prater: use Erigon EL node if available

https://github.com/status-im/infra-nimbus/blob/9aa83f8d47d08eea86e7cd34fb4bd1c2ae50a6e6/ansible/group_vars/nimbus.prater.yml#L102-L105
```
admin@linux-05.he-eu-hel1.nimbus.prater:~ % s cat beacon-node-prater-unstable | grep '\--el='
    --el=http://localhost:8554 \
    --el=http://localhost:9554 \
```
```
admin@linux-06.he-eu-hel1.nimbus.prater:~ % s cat beacon-node-prater-unstable | grep '\--el='
    --el=http://localhost:8554 \
    --el=http://localhost:9554 \
```

**Comment by jakubgs** [comment]
I'm still seeing these errors:
```json
{"err":"Clique.Seal: unauthorized signer","lvl":"warn","msg":"Block sealing failed","t":"2023-03-22T11:28:19.882943451Z"}
```
So I need to figure out what's causing this.

**Comment by jakubgs** [comment]
Enabled metrics for Erigon:

- https://github.com/status-im/infra-role-consul-service/commit/4d7c9c60 - support disabled option for services
- https://github.com/status-im/infra-role-erigon/commit/02030bcc - consul: add metrics service definition
- https://github.com/status-im/infra-role-erigon/commit/e4082d94 - consul: optional rpc, authrcp, and metrics services
- https://github.com/status-im/infra-role-erigon/commit/a838e5ad - docker: add missing bool flag for metrics
- https://github.com/status-im/infra-role-erigon/commit/8fc4f1cb - docker: make service ports mapping optional
- https://github.com/status-im/infra-nimbus/commit/0956c88d - nimbus.prater: enable metrics for Erigon nodes

And the endpoint works, but `/metrics` gives 404:
```
admin@linux-05.he-eu-hel1.nimbus.prater:~ % c 0:7063/metrics
404 page not found
curl: (22) The requested URL returned error: 404
```

**Comment by jakubgs** [comment]
On `linux-06` we can see the increased disk utilization by Erigon:

![image](https://user-images.githubusercontent.com/2212681/227183040-f9136e22-2be2-43f4-924b-8f738e305acf.png)

But for some reason both `linux-05` and `linux-06` were found offline today.

**Comment by jakubgs** [comment]
I opened tickets with Hetzner about this. The hosts just stopped. Nothing in the logs indicates what happened:
#### `linux-05.he-eu-hel1.nimbus.prater`
```
Mar 22 17:52:33 linux-05.he-eu-hel1.nimbus.prater systemd[1]: Configuration file /etc/systemd/system/build-beacon-node-prater-testing.timer is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Mar 22 17:52:33 linux-05.he-eu-hel1.nimbus.prater systemd[1]: Configuration file /etc/systemd/system/build-beacon-node-prater-testing.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
-- Boot c101c66b971c490aa3216d931f0abc4f --
Mar 23 10:58:34 linux-05.he-eu-hel1.nimbus.prater kernel: Linux version 5.15.0-48-generic (buildd@lcy02-amd64-080) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 (Ubuntu 5.15.0-48.54-generic 5.15.53)
Mar 23 10:58:34 linux-05.he-eu-hel1.nimbus.prater kernel: Command line: BOOT_IMAGE=/vmlinuz-5.15.0-48-generic root=UUID=68d2e348-7a64-4841-bb9a-85560a9e93b7 ro consoleblank=0 systemd.show_status=true nomodeset consoleblank=0
Mar 23 10:58:34 linux-05.he-eu-hel1.nimbus.prater kernel: KERNEL supported cpus:
```
#### `linux-06.he-eu-hel1.nimbus.prater`
```
Mar 23 08:26:23 linux-06.he-eu-hel1.nimbus.prater systemd[1]: Configuration file /etc/systemd/system/resync-beacon-node-prater-stable.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Mar 23 08:26:23 linux-06.he-eu-hel1.nimbus.prater systemd[1]: Configuration file /etc/systemd/system/resync-beacon-node-prater-stable.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
-- Boot 4d25befadf8244bcadc0d41e6643752c --
Mar 23 10:58:49 linux-06.he-eu-hel1.nimbus.prater kernel: Linux version 5.15.0-67-generic (buildd@lcy02-amd64-116) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 (Ubuntu 5.15.0-67.74-generic 5.15.85)
Mar 23 10:58:49 linux-06.he-eu-hel1.nimbus.prater kernel: Command line: BOOT_IMAGE=/vmlinuz-5.15.0-67-generic root=UUID=7aa251a7-6651-4100-8222-fa942ddc28a8 ro nomodeset consoleblank=0
```

**Comment by jakubgs** [comment]
It appears to be syncing based on disk usage:
```
admin@linux-06.he-eu-hel1.nimbus.prater:~ % sudo du -hs /docker/erigon-goerli-03
215G	/docker/erigon-goerli-03
```
But RPC call response shows that current block is zero:
```
admin@linux-06.he-eu-hel1.nimbus.prater:~ % /docker/erigon-goerli-03/rpc.sh eth_syncing | jq '.result | { currentBlock, highestBlock }'
{
  "currentBlock": "0x0",
  "highestBlock": "0x81b31f"
}
```
Which doesn't make any sense.

**Comment by jakubgs** [comment]
I think this metric indicates the sync progress currently:
```
admin@linux-06.he-eu-hel1.nimbus.prater:~ % c 0:7063/debug/metrics/prometheus | grep '^sync' | grep execution
sync{stage="execution"} 8469787
admin@linux-06.he-eu-hel1.nimbus.prater:~ % c 0:7063/debug/metrics/prometheus | grep '^sync' | grep execution
sync{stage="execution"} 8470418
admin@linux-06.he-eu-hel1.nimbus.prater:~ % c 0:7063/debug/metrics/prometheus | grep '^sync' | grep execution
sync{stage="execution"} 8471146
```

**Comment by jakubgs** [comment]
I have opened the metrics port and configured a scrape job:

- https://github.com/status-im/infra-role-erigon/commit/a703f38b - consul: use a common name for metrics service
- https://github.com/status-im/infra-role-erigon/commit/8582b643 - consul: add container name to metrics service
- https://github.com/status-im/infra-nimbus/commit/d6de0faf - nimbus.prater: open Erigon metrics port on VPN
- https://github.com/status-im/infra-hq/commit/cfb339ba - prometheus-slave: add erigon-metrics job

And it works.

**Comment by jakubgs** [comment]
Looks like `linux-05` finished syncing:
```
admin@linux-05.he-eu-hel1.nimbus.prater:~ % /docker/erigon-goerli-03/rpc.sh eth_syncing
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": false
}
```
But the host shut down again for no reason, so I asked the Hetzner support to replace the motherboard and power supplies.

**Comment by jakubgs** [comment]
Looks like it's working:

#### `linux-05.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/229518046-2b7af832-a494-4e55-9c79-933fe7039291.png)

#### `linux-06.he-eu-hel1.nimbus.prater`

![image](https://user-images.githubusercontent.com/2212681/229517822-58927076-7d4f-45af-a17e-e4cc00eaa6fb.png)

---
I'm closing as done.
