### ISSUE TITLE
Add support for Grafana metrics derived from logs

### ISSUE THREAD

**Issue by zah** [status-im/infra-nimbus#146]
The [Loki add-on](https://grafana.com/oss/loki/) for Grafana can enable us to define metrics such as "Total number of error messages", "Total logging volume", etc. It will also allow us to quickly browse the logs correlated with certain events such as spikes in CPU usage, loss of peers, etc.

**Comment by jakubgs** [comment]
We aggregate logs with ELK stack, not with Loki.
