### ISSUE TITLE
Deploy a few nodes with `--enable-yamux=true`

### ISSUE THREAD

**Issue by Menduist** [status-im/infra-nimbus#148]
Added a new flag to nimbus `unstable`:

* https://github.com/status-im/nimbus-eth2/pull/5080

Could it be set to `--enable-yamux=true` on `linux-07.ih-eu-mda1.nimbus.mainnet` libp2p 3 & libp2p 4 nodes.

**Comment by jakubgs** [comment]
Done:

- https://github.com/status-im/infra-nimbus/commit/de28d461 - nimbus.mainnet: enable yamux for 2 libp2p nodes

https://github.com/status-im/infra-nimbus/blob/de28d46133e290bcd17d25b4f92029cd7fe2f25b/ansible/group_vars/nimbus.mainnet.yml#L168-L173
Effect:
```
admin@linux-07.ih-eu-mda1.nimbus.mainnet:~ % grep yamux /etc/systemd/system/beacon-node-mainnet-libp2p-*.service
/etc/systemd/system/beacon-node-mainnet-libp2p-03.service:    --enable-yamux=true
/etc/systemd/system/beacon-node-mainnet-libp2p-04.service:    --enable-yamux=true
```
