### ISSUE TITLE
Unstable Prater host due to OOM

### ISSUE THREAD

**Issue by apentori** [status-im/infra-nimbus#151]
# Description

The prater host linux-06.ih-eu-mda1.nimbus.prater  is unstable and often require restart of the beacon nodes hosted.

## Details

The host lack memory for the usage: In less than 72 hours, 3 process where OOM killed (docker container or beacon node).

![image](https://github.com/status-im/infra-nimbus/assets/124469871/0f87dc70-8bbd-40f0-addb-9dd63219a0dd)
![image](https://github.com/status-im/infra-nimbus/assets/124469871/149b8233-955f-4da2-a341-779c45196f4d)

https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?orgId=1&refresh=1m&var-host=linux-06.ih-eu-mda1.nimbus.prater&from=now-72h&to=now

Compared to other host where the memory usage is more stable

linux-03
![image](https://github.com/status-im/infra-nimbus/assets/124469871/a5289c7e-f02d-4e43-8170-abfc612d1441)

linux-04 
![image](https://github.com/status-im/infra-nimbus/assets/124469871/c3f942b5-1513-4e56-ac54-81374e539524)

Those OOM tends to block a beacon node until it is restarted : https://grafana.infra.status.im/d/pgeNfj2Wz23/nimbus-beacon-node?orgId=1&var-instance=linux-06.ih-eu-mda1.nimbus.prater&var-container=beacon-node-prater-testing&from=1690977600000&to=1691064000000

## Proposition

Here are some action we could do to reduce the issue

1. Remove the Erigon instance.
2. Remove some validator clients (linked to the `testing` and `libp2p` beacon node instances),.
3. Change the validator layout to be less dense (almost 30k validator on the host).
4. Increase Host Memory.

**Comment by jakubgs** [comment]
@zah could you please help us make the right decision here? What makes the most sense for you?

**Comment by jakubgs** [comment]
I have adjusted the max header size to the default of 128 KB:

- https://github.com/status-im/infra-nimbus/commit/5586db72 - nimbus.prater: reduce max_headers_size to 128 KB
- https://github.com/status-im/infra-nimbus/commit/45d52614 - nimbus.prater: bump limits for consul alerts on linux-06

Definitely made a difference:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/a79eaefd-be27-449e-be91-924e8ff110d7)

The socket usage graph looks flat now, no idea why though. And memory looks healthier too:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/69619b1f-1184-4f01-b0e9-3909c8f635a9)

Not sure why header size reduced socket usage though.

**Comment by jakubgs** [comment]
There still appears to be an upward trend with used sockets:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/3486eba4-0b0b-421a-9324-a256738c1c31)

So the actual issue is not solved, but at least memory usage is reasonable for now, and if restarts happen often enough it should not become a problem.

**Comment by yakimant** [comment]
Last OOM happened on 04/08/2023.

Free/Cached memory looks good since 07/08/2023:
<img width="677" alt="Screenshot 2023-08-14 at 17 30 41" src="https://github.com/status-im/infra-nimbus/assets/1529006/5ba03fef-94c9-411f-a578-73899a065b37">

But open sockets is still a lot:
<img width="674" alt="Screenshot 2023-08-14 at 17 31 51" src="https://github.com/status-im/infra-nimbus/assets/1529006/e5eb6d4a-2f09-4ac8-90bd-4423246cf196">

beacon-node (libp2p) and validator-client (testing) had some issues and reboot helped.
Shall we have a nightly reboot?

**Comment by yakimant** [comment]
It took 4-5h to reclaim the 100k sockets back and metrics issues to appear again.

**Comment by yakimant** [comment]
Most sockets opened by these 3 proccesses:
```
$ sudo find /proc/*/fd -lname 'socket:*' 2> /dev/null | wc -l
80942
$ sudo find /proc/*/fd -lname 'socket:*' 2> /dev/null | cut -d/ -f3 | uniq -c | sort | tail -3
  24757 2513632
  25540 2614277
  28355 2590745
$ sudo find /proc/*/fd -lname 'socket:*' 2> /dev/null | cut -d/ -f3 | uniq -c | sort | tail -3 | awk '{print $2}' | xargs -I_ ps -p _ -o command | grep -v COMMAND | cut -d" " -f1 | cut -d\/ -f3
validator-client-prater-testing
beacon-node-prater-testing
beacon-node-prater-libp2p
```

`stable` and `unstable` beacon nodes have a lot of validator, but don't have so many sockets open.

**Comment by jakubgs** [comment]
It looks like @cheatfate is working on this issue.

**Comment by cheatfate** [comment]
We still working on this issue, and it would not be fast, so i think it will not be fixed until next release (current release is 23.8.0).

**Comment by jakubgs** [comment]
Thanks for the update, appreciate it. I can see the issue indeed persists:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/bb04fc9c-863c-4d37-80fe-06e915349abb)

![image](https://github.com/status-im/infra-nimbus/assets/2212681/42368b92-745c-49e1-833c-cc1e72b27675)

Very large numbers of sockets being used, as expected.

**Comment by yakimant** [comment]
Note, that, consule service settings were ammended to notify roughly once a week.
<details>
```
$ sudo grep "interval\|failures" /etc/consul/service_{beacon,validator}*
/etc/consul/service_beacon_node_prater_chronos.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_chronos.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_chronos.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_chronos.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_chronos.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_chronos.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_libp2p.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_libp2p.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_libp2p.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_libp2p.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_libp2p.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_libp2p.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_stable.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_stable.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_stable.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_stable.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_stable.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_stable.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_testing.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_testing.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_testing.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_testing.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_testing.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_testing.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_unstable.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_unstable.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_unstable.json:          "failures_before_critical": 200
/etc/consul/service_beacon_node_prater_unstable.json:          "interval": "1h",
/etc/consul/service_beacon_node_prater_unstable.json:          "failures_before_warning": 100,
/etc/consul/service_beacon_node_prater_unstable.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_chronos.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_chronos.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_chronos.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_chronos.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_chronos.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_chronos.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_libp2p.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_libp2p.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_libp2p.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_libp2p.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_libp2p.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_libp2p.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_testing.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_testing.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_testing.json:          "failures_before_critical": 200
/etc/consul/service_validator_client_prater_testing.json:          "interval": "1h",
/etc/consul/service_validator_client_prater_testing.json:          "failures_before_warning": 100,
/etc/consul/service_validator_client_prater_testing.json:          "failures_before_critical": 200
```
</details>
Don't forget to revert after `linux-06` is good again.

**Comment by jakubgs** [comment]
It appears the number of used sockets has stabilized:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/bf89ee90-0834-43c1-9e79-64b3b08b73af)

I think we can close this for now.
