### ISSUE TITLE
Nim 2.0 version testing

### ISSUE THREAD

**Issue by etan-status** [status-im/infra-nimbus#165]
It would be great if some of the Nimbus deployments would be compiled using Nim `upstream/version-2-0` with `--mm:refc` instead of the default 1.6 version. `upstream/version-2-0` has been stable as far as compilation is concerned for quite a while now.

Right now, especially on Windows there still are issues with multithreading, so expecting instability there. Seeing that confirmed on the fleet as well, and seeing whether macOS / Linux exhibit issues would be great to track when things improve. Problem visible in eg https://github.com/cheatfate/nimcrypto/actions/runs/7306516072/job/19911286657

Have to make sure to use `NIM_COMMIT=upstream/version-2-0` instead of just `version-2-0` because sometimes people push outdated `version-2-0` branch to `origin` (status-im fork). The Nim build script adds a second remote `upstream` that tracks nim-lang repo. Can also see nimbus-eth2 CI for the config. And, the `--mm:refc` needs to be passed as well from 2.0 onward as the default got changed to orc. It's fine to also pass --mm:refc to 1.6 but there it's a nop as it's already the default.

**Comment by tersec** [comment]
https://github.com/status-im/infra-nimbus/pull/167 but didn't check whether it gets `--mm:refc` correct. Depending on how it's built, this is part of https://github.com/status-im/nimbus-eth2/blob/c5cb0ea3f6ec0ad3af76524ea7ec0eb1da0b973d/config.nims#L139
```nim
--mm:refc
```

**Comment by jakubgs** [comment]
I believe since Nim 2.0 is already in `unstable` this is no longer relevant.

**Comment by jakubgs** [comment]
And please ping us in issues, we don't check every repo for new issues.
