### ISSUE TITLE
Fluffy nodes on one host with multiple IP vs separate instances

### ISSUE THREAD

**Issue by kdeme** [status-im/infra-nimbus#186]
We want to have many more (+92) but much smaller Fluffy nodes added to our fleet (for which a ticket will be created).
In order to decide on the infra setup it would be good to know the cost of adding IPs to machines as we have now for the fleet. And how many can be added per machine.

Next that that, it would also be good to know the cost of one of our current machines or similar vs single instances (with say 2 to 4GB of storage).

@jakubgs

**Comment by jakubgs** [comment]
I have investigated the cost of extra IPv4 addresses from InnovaHosting - where most of our Nimbus servers lives - and they came back with an answer:

>32 IP addresses will cost annually €768.00.

https://client.innovahosting.net/viewticket.php?tid=779731&c=sNktS7Is

Which is 24 EUR per IP per year, or 2 EUR per month, which is close to 1.70 EUR Hetzner charges.
https://docs.hetzner.com/general/others/ipv4-pricing/

**Comment by jakubgs** [comment]
Currently we have 2 InnovaHosting servers running 32 nodes each which cost 1868.40 EUR annually, 156 EUR monthly.
Together with extra IPs they would cost 180 EUR.

The cost of 32 DigitalOcean droplets of type `s-1vcpu-2gb` with 80 GB of storage would cost `(32+5) * 12 = 444 EUR`.

**Comment by jakubgs** [comment]
Forgot to add that we would need to expand the storage of current fluffy nodes from 1.5 TB to 3 TB so that would increase the price above 180 EUR, probably to 200 EUR.

**Comment by jakubgs** [comment]
In relation to this I have fixed access via IPv6 addresses to a few hosts:

- [`infra-nimbus#68c34797`](https://github.com/status-im/infra-nimbus/commit/68c34797) - mainnet,sepolia,holesky: fix IPv6 addresses

I have also added docs to the repo about available to us IPv6 ranges:
https://github.com/status-im/infra-nimbus/blob/68c347973f2ea3e4aba852df6bee18c770f53973/INNOVA_HOSTING.md?plain=1#L5-L31

I have also asked their support about adding multiple addresses per host and their answer was positive:

>You may attach multiple addresses, but not too many like >200

https://client.innovahosting.net/viewticket.php?tid=511540&c=CK47WhKT

**Comment by kdeme** [comment]
OK, so if I understand correctly:
- Price of droplets vs single host with multiple services is roughly double for the droplets
- There is no issue in adding multiple addresses, at least to some sane limit that we would not reach

**Comment by jakubgs** [comment]
We don't pay for extra IPv6 addresses, so it would be nearly 3x cheaper actually.

**Comment by jakubgs** [comment]
Why did you close it? Do you not want the extra addresses?

**Comment by kdeme** [comment]
> Why did you close it? Do you not want the extra addresses?
I considered this ticket purely the investigation on price/possiblities :), but sure.

> We don't pay for extra IPv6 addresses, so it would be nearly 3x cheaper actually.
OK, but we do still want the IPv4 addresses also. With only IPv6 it would not be possible for IPv4 only nodes to reach our fleet.

**Comment by jakubgs** [comment]
I would assume it would be lower. I asked them about 32 addresses and they said that would be fine, not sure about more.

**Comment by jakubgs** [comment]
So, shall I put in a budget request for the extra 32 IPs per node for two hosts for the 1868.40 EUR annually?

**Comment by kdeme** [comment]
> So, shall I put in a budget request for the extra 32 IPs per node for two hosts for the 1868.40 EUR annually?

Yes, I think we should go forward with this so that we can apply proper IP limits to our nodes.
We can however get away with 16 IPs as the current default setting would allow to connect to two different nodes with the same IP.

Ideally we can also keep the IPs the same for the  4 bootstrap nodes (which are the first 2 nodes on each machine). But if that is too much of a hassle for some reason, it is fairly simply to update those ENRs.

**Comment by jakubgs** [comment]
I've requested the budget for this purchase: https://prod.mod.spiff.status.im/i/7361

**Comment by jakubgs** [comment]
The request for budget was approved and I have requested the addition of these 64 addresses to two fluffy hosts:
https://client.innovahosting.net/viewticket.php?tid=232217&c=M4FFpKeK

**Comment by jakubgs** [comment]
The support responded with;

>I have created invoice for 2 blocks of 32 ipv4 addresses. After payment we will configure them as ROUTED ipv4 prefix toward mentioned servers. If you are planning to bridge eth0 (first port) of server with a virtual machines (i don't know), then let us know about that, we will configure ip addresses in other way.

I have paid the invoice and requested a direct attachment of the IP address to the host.

**Comment by jakubgs** [comment]
The new addresses have been routed to the hosts:

>We have allocated following ipv4 prefixes:
>
>194.33.43.32/27 is routed to metal-01.ih-eu-mda1.nimbus.fluffy(194.33.40.238)
>194.33.43.64/27 is routed to metal-02.ih-eu-mda1.nimbus.fluffy(194.33.40.239)
>
>You may add ip address like 194.33.43.32/27 to the node, but default gateway remain the same 194.33.40.1

https://client.innovahosting.net/viewticket.php?tid=232217&c=M4FFpKeK

**Comment by jakubgs** [comment]
I have configured the IP addresses and the nodes to use them:

- [`infra-nimbus#ae6ee82a`](https://github.com/status-im/infra-nimbus/commit/ae6ee82a) - fluffy: add netplan role to manage network config
- [`infra-nimbus#a303fc92`](https://github.com/status-im/infra-nimbus/commit/a303fc92) - fluffy: add extra 32 addreses to each host
- [`infra-nimbus#032dc7dd`](https://github.com/status-im/infra-nimbus/commit/032dc7dd) - fluffy: fix using tags with nimbus-fluffy role
- [`infra-nimbus#567e9531`](https://github.com/status-im/infra-nimbus/commit/567e9531) - fluffy: use separate IPv4 addresses for each node
- [`infra-nimbus#d2d277a0`](https://github.com/status-im/infra-nimbus/commit/d2d277a0) - fluffy: make all nodes use the same port 9100

I have also switched the UDP listening port from a dynamically generated one to `9100` for all nodes to simplify things.

Looks like this:
```
jakubgs@metal-01.ih-eu-mda1.nimbus.fluffy:~ % grep listen-address /etc/systemd/system/nimbus-fluffy-mainnet-master-*.service 
/etc/systemd/system/nimbus-fluffy-mainnet-master-01.service:  --listen-address=194.33.43.33 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-02.service:  --listen-address=194.33.43.34 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-03.service:  --listen-address=194.33.43.35 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-04.service:  --listen-address=194.33.43.36 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-05.service:  --listen-address=194.33.43.37 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-06.service:  --listen-address=194.33.43.38 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-07.service:  --listen-address=194.33.43.39 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-08.service:  --listen-address=194.33.43.40 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-09.service:  --listen-address=194.33.43.41 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-10.service:  --listen-address=194.33.43.42 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-11.service:  --listen-address=194.33.43.43 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-12.service:  --listen-address=194.33.43.44 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-13.service:  --listen-address=194.33.43.45 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-14.service:  --listen-address=194.33.43.46 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-15.service:  --listen-address=194.33.43.47 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-16.service:  --listen-address=194.33.43.48 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-17.service:  --listen-address=194.33.43.49 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-18.service:  --listen-address=194.33.43.50 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-19.service:  --listen-address=194.33.43.51 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-20.service:  --listen-address=194.33.43.52 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-21.service:  --listen-address=194.33.43.53 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-22.service:  --listen-address=194.33.43.54 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-23.service:  --listen-address=194.33.43.55 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-24.service:  --listen-address=194.33.43.56 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-25.service:  --listen-address=194.33.43.57 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-26.service:  --listen-address=194.33.43.58 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-27.service:  --listen-address=194.33.43.59 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-28.service:  --listen-address=194.33.43.60 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-29.service:  --listen-address=194.33.43.61 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-30.service:  --listen-address=194.33.43.62 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-31.service:  --listen-address=194.33.43.63 \
/etc/systemd/system/nimbus-fluffy-mainnet-master-32.service:  --listen-address=194.33.43.64 \
```

**Comment by jakubgs** [comment]
Not sure if this means the nodes have no peers:
```
jakubgs@metal-01.ih-eu-mda1.nimbus.fluffy:~ % for PORT in $(seq 9201 9233); do curl -s 0:$PORT/metrics | grep '^rlpx_connected_peers '; done
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
rlpx_connected_peers 0.0
```
But it doesn't seem right.

**Comment by jakubgs** [comment]
The graphs suggest that the nodes are fine:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/4e1e5d7d-228a-4d43-932f-063eb0fc74c3)

But maybe you can confirm that they are fine after setting the separate IP addresses and new port @kdeme ?

**Comment by jakubgs** [comment]
Found an off-by-one error:

- [`infra-nimbus#c4057116`](https://github.com/status-im/infra-nimbus/commit/c4057116) - nimbus.fluffy: fix off by one error in port icrements

**Comment by kdeme** [comment]
> But it doesn't seem right.

Not an issue. Fluffy doesn't use rlpx so the `rlpx_connected_peers` metric is useless to us. Not sure how it leaked into the metrics. I'll see if I can get rid of it easily.

**Comment by jakubgs** [comment]
Okay, then I'll consider this done. If you find any problems you can reopen this issue.
