### ISSUE TITLE
Test about 1k of existing validators on one or two nodes with Primev `mev-commit`

### ISSUE THREAD

**Issue by tersec** [status-im/infra-nimbus#188]
https://docs.primev.xyz/get-started/validators

**Comment by jakubgs** [comment]
My understanding is that this involves selecting a few nodes from one Holesky host, and staking their validators on Primev.

For example nodes with 700 validators each would be a good candidate probably:
https://github.com/status-im/infra-nimbus/blob/4555e37bde63dc530f4eac392e3557a7c5e86157/ansible/vars/layout/holesky.yml#L47-L51

@tersec would you rather have all nodes on one host? Or would you prefer a spread across the 3 types of EL nodes we have?
If so nodes with 400 validators each would probably make most sense.

Also, would we prefer a specific BN branch, like `unstable`, or dies it no matter in this case?

**Comment by shaspitz** [comment]
Hey all! Seems like you're on the right track here. The only thing you'll need from the validator registry contract's perspective is an EOA with some eth and the list of BLS pubkeys that will be staked in batches. How those validator pubkeys correspond to your node config is up to you. Lmk if you have any questions about the opt in process

**Comment by techgangboss** [comment]
hey guys let us know if we can finalize this, we'll be announcing the dashboard soon and would love to involve your validators (and support from Nimbus. we won't be mentioning names however unless you'd like for us to)

**Comment by yakimant** [comment]
Alright, here is what I understand what we need:

1. mev-boost service
  a. https://docs.flashbots.net/flashbots-mev-boost/getting-started/installation
  b. configure with Tital relay (which supports `mev-commit`: https://docs.titanrelay.xyz/)
2. configure `nimbus` to use `mev-boost`: https://nimbus.guide/external-block-builder.html - [Already in Ansible role](https://github.com/status-im/infra-nimbus/blob/master/ansible/group_vars/nimbus.holesky.yml#L100-L101)
3. List of validator keys
4. 0.0001 ETH x 1k validators ~ 0.1 ETH to stake
5. register at https://validators.mev-commit.xyz

Correct me if I'm wrong with list or order.

**Comment by shaspitz** [comment]
> Alright, here is what I understand what we need:
> 
> * [ ]  `mev-boost` service
>   a. https://docs.flashbots.net/flashbots-mev-boost/getting-started/installation
>   b. configure with Tital relay (which supports `mev-commit`: https://docs.titanrelay.xyz/)
> * [ ]  configure `nimbus` to use `mev-boost`: https://nimbus.guide/external-block-builder.html - [Already in Ansible role](https://github.com/status-im/infra-nimbus/blob/master/ansible/group_vars/nimbus.holesky.yml#L100-L101)
> * [ ]  List of validator keys
> * [ ]  0.0001 ETH x 1k validators ~ 0.1 ETH to stake
> * [ ]  register at https://validators.mev-commit.xyz
> 
> Correct me if I'm wrong with list or order.

Sounds correct to me!

**Comment by yakimant** [comment]
`mev-boost` - `beacon-node` works well according to the logs:

`beacon-node`:
```
{"lvl":"INF","ts":"2024-08-13 12:18:40.170+00:00","msg":"Using external payload builder","topics":"beacnde","payloadBuilderUrl":"http://localhost:18550"}
{"lvl":"DBG","ts":"2024-08-13 12:19:23.403+00:00","msg":"Sending REST request to remote server","remote":"localhost:18550","request":"/eth/v1/builder/validators","http_method":"POST"}
{"lvl":"DBG","ts":"2024-08-13 12:19:23.404+00:00","msg":"Opened connection to remote server","remote":"localhost:18550","request":"/eth/v1/builder/validators","http_method":"POST"}
{"lvl":"DBG","ts":"2024-08-13 12:19:23.428+00:00","msg":"REST request body has been sent","remote":"localhost:18550","request":"/eth/v1/builder/validators","size":160005,"http_method":"POST"}
{"lvl":"DBG","ts":"2024-08-13 12:19:23.962+00:00","msg":"Got REST response headers from remote server","remote":"localhost:18550","request":"/eth/v1/builder/validators","status":200,"http_method":"POST"}
{"lvl":"DBG","ts":"2024-08-13 12:19:23.962+00:00","msg":"Received REST response body from remote server","remote":"localhost:18550","request":"/eth/v1/builder/validators","contentType":"application/json","size":3}
```

`mev-boost`:
```
time="2024-08-13T12:19:23.961Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.557093 method=POST path=/eth/v1/builder/validators status=200
```

**Comment by yakimant** [comment]
Keys (1600): 
[geth-07.ih-eu-mda1.nimbus.holesky.keys.txt](https://github.com/user-attachments/files/16599822/geth-07.ih-eu-mda1.nimbus.holesky.keys.txt)

**Comment by yakimant** [comment]
To get the Holesky ETH with Metamask:
1. Switch to Holesky network: https://chainid.network
2. Increase score 2+: https://passport.gitcoin.co
3. Geth ETH: https://holesky-faucet.pk910.de

**Comment by yakimant** [comment]
Hm, UI looks broken:
<img width="1016" alt="Screenshot 2024-08-13 at 15 19 51" src="https://github.com/user-attachments/assets/e104fa48-fa73-4dd9-8b23-7b486f5f900f">

**Comment by yakimant** [comment]
Tested on a different brawser (Brave) - same issue.

**Comment by taylorjdawson** [comment]
@yakimant do you see anything in your console logs?

**Comment by yakimant** [comment]
```
Object { details: "execution reverted", docsPath: undefined, metaMessages: undefined, shortMessage: "Execution reverted for an unknown reason.", name: "ExecutionRevertedError", version: "viem@2.9.25", message: "Execution reverted for an unknown reason.\n\nDetails: execution reverted\nVersion: viem@2.9.25", cause: InvalidInputRpcError }
page-c27b5514437b518b.js:1:15139
```

```
{
  "details": "execution reverted",
  "shortMessage": "Execution reverted for an unknown reason.",
  "name": "ExecutionRevertedError",
  "version": "viem@2.9.25",
  "message": "Execution reverted for an unknown reason.\n\nDetails: execution reverted\nVersion: viem@2.9.25",
  "cause": {
    "message": "Missing or invalid parameters.\nDouble check you have provided the correct parameters.\n\nURL: https://ethereum-holesky-rpc.publicnode.com\nRequest body: {\"method\":\"eth_estimateGas\",\"params\":[{\"data\":\"0xLONG_HEX_HERE\",\"from\":\"0x65d582e3c01c2b3cf14cd4dbee6335727c659f1d\",\"to\":\"0x5d4fC7B5Aeea4CF4F0Ca6Be09A2F5AaDAd2F2803\",\"value\":\"0x6a94d74f430000\"}]}\n\nDetails: execution reverted\nVersion: viem@2.9.25"
  }
}
```

**Comment by yakimant** [comment]
FYI @taylorjdawson

**Comment by taylorjdawson** [comment]
@yakimant Just deployed a fix 🔨let me know if have any more issues!

**Comment by yakimant** [comment]
Thanks @taylorjdawson, it works!

Found another bug (non-blocking, with workaround).

Page appears with valid minimum stake value, but still with error:
<img width="854" alt="Screenshot 2024-08-19 at 12 13 08" src="https://github.com/user-attachments/assets/a5757e1a-f065-4960-b004-c35b2404b3e1">

If I try to re-enter `0.0001` - it's fine (I used it to proceed):
<img width="850" alt="Screenshot 2024-08-19 at 12 14 00" src="https://github.com/user-attachments/assets/91c326e6-06d0-4eaa-9a57-2fab336e7865">

But if I try `0.0002` it has an issue again:
<img width="862" alt="Screenshot 2024-08-19 at 12 14 04" src="https://github.com/user-attachments/assets/afa59903-c36e-4619-80d5-3cb71c1be593">

**Comment by yakimant** [comment]
Ok web tool finished (without success message).
So I suppose all setup it done, who can check it?
@tersec

**Comment by yakimant** [comment]
Everything was setup according to my understanding. No issues on the graphs.
Feel free to test and reopen if needed.
