### ISSUE TITLE
Increase Sepolia gas limit to 36,000,000 across all sepolia nodes

### ISSUE THREAD

**Issue by tersec** [status-im/infra-nimbus#217]
The default gas limit has been 30M.

One way to do this is `--suggested-gas-limit=36000000`.

Geth needs `--miner.gaslimit 36000000`.

**Comment by tersec** [comment]
Better to update the defaults:
- https://github.com/status-im/nimbus-eth2/pull/6763

**Comment by tersec** [comment]
Reopening because while Nimbus will support 36M by default, and Nethermind 1.30.0 or newer [also increases the limit to 36M by default](https://github.com/NethermindEth/nethermind/releases/tag/1.30.0), Geth might not.

**Comment by yakimant** [comment]
Done
