### ISSUE TITLE
New layout of Nimbus nodes

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#23]
We will need a new layout of Nimbus nodes in the fleet. All hosts will be in the `madella` network:

* 4 hosts running `master` branch
* 4 hosts running `devel` branch
* 2 hosts running `nim-libp2p-auto-bump` branch

Each node should have its Docker image updated every 24 hours, but with an offset so as to not synchronize restarts across hosts.

There are 1024 validator keys we posses. Those are currently stored in `master-01` and `slave-01` to `05`. Those need to be spread out so all 10 of `madella` network nodes have their own.

They are stored under `secrets` and `validators` subfolders of the node `data.dir`:
```
admin@node-01.aws-eu-central-1a.nimbus.test:~ % sudo ls -l /data/beacon-node-testnet3/data/shared_medalla_0 | grep -E '(secrets|validators)'
drwxr-xr-x   2 dockremap dockremap 28672 Aug  3 17:26 secrets
drwxr-xr-x 172 dockremap dockremap 32768 Sep 16 13:10 validators
```
They need to be transferred in matching pairs.

Details: https://status-im.github.io/nimbus-eth2/medalla.html?highlight=validators#key-management

**Comment by arnetheduck** [comment]
let's do 4/4 for master/develop and remaining 2 for libp2p

**Comment by jakubgs** [comment]
Here's the new layout: https://github.com/status-im/infra-nimbus/commit/652c7129

I'm in the process of rebuilding nodes and re-distributing validators. I think I'll do 10*100 with extra 24 on the master.

**Comment by jakubgs** [comment]
Oh... your branch is called `devel` not `develop`. That confused me for a bit.

**Comment by jakubgs** [comment]
Useful command for cleaning up old timers/serivces:
```
sudo systemctl list-unit-files --type=timer | grep beacon | cut -d' ' -f1
```

**Comment by jakubgs** [comment]
The new layout is deployed with the validators spread being: 100 per host, and additional 24 for master.

The setup for building of images is gonna come tomorrow.

**Comment by stefantalpalaru** [comment]
46 validators on master-01 are missing their "keystore.json" files:

```text
root@master-01:/home/stefan# for D in /docker/beacon-node-testnet3-master/data/shared_medalla_0/validators/*; do [[ -d $D && ! -e $D/keystore.json ]] && echo $D; done | wc -l
46
root@master-01:/home/stefan# ls /docker/beacon-node-testnet3-master/data/shared_medalla_0/validators/*/keystore.json | wc -l
78
```

**Comment by jakubgs** [comment]
good catch

**Comment by stefantalpalaru** [comment]
It's in a restart loop because of this:

```text
Nov  5 22:18:12 master-01.aws-eu-central-1a.nimbus.test docker/beacon-node-testnet3-master[645]: {"lvl":"ERR","ts":"2020-11-05 22:18:12.075+00:00","msg
":"Failed to read keystore","tid":1,"file":"keystore_management.nim:224","err":"No such file or directory\nAdditional info: \"/data/shared_medalla_0/va
lidators/85d5c498977285814ac77d15551d58663b5c3e35c743cc210f1318595610b6c81c25e647265d691a7b7b2ad5caee3112/keystore.json\"","path":"/data/shared_medalla
_0/validators/85d5c498977285814ac77d15551d58663b5c3e35c743cc210f1318595610b6c81c25e647265d691a7b7b2ad5caee3112/keystore.json"}
```
I think more nodes are affected, judging by `docker ps` runtimes.

**Comment by stefantalpalaru** [comment]
If you lost track of validator data, after moving them around, here are the originals: https://github.com/status-im/nimbus-private/tree/master/medalla_deposits

**Comment by jakubgs** [comment]
Nah, I made backups, obviously.

**Comment by jakubgs** [comment]
Btw, github private repos are a really bad place to store private data. Yeah, they are not public, but they are not encrypted, so they could easily leak.

**Comment by jakubgs** [comment]
The other ones were issues with permissions. Forgot to change after copying over the sqlite db.

**Comment by jakubgs** [comment]
Cleaned up old logs using:
```
ansible all -m shell -a "find /docker/log -mindepth 1 -maxdepth 1 | grep -vE 'beacon-node-testnet3-(master|devel|libp2p)' | xargs sudo rm -r"
```
Not sure why but this:
```
ansible 'all[0]' -m shell -a "echo $(docker ps -q --format={%raw%}'{{ .Names }}'{%endraw%} )"  
```
Returns no result, even though it works without the `echo`.

**Comment by jakubgs** [comment]
I deployed the automated building of branches in: https://github.com/status-im/infra-nimbus/commit/7888b437
Also added docs in: https://github.com/status-im/infra-nimbus/commit/f484a861

Enabled autoupdated of containers with Watchtower in: https://github.com/status-im/infra-role-beacon-node/commit/4dc6c9e9

**Comment by jakubgs** [comment]
Looks like build process was broken in: https://github.com/status-im/nimbus-eth2/commit/e9b9cd75
```
Building: install/usr/lib/libbacktracenim.a
make: *** No rule to make target 'signing_process'.  Stop.
make: *** Waiting for unfinished jobs....
```
The targets were renamed to `nimbus_beacon_node` and `nimbus_signing_process` but only one was made backwards compatible in https://github.com/status-im/nimbus-eth2/commit/beb376c3a5e868664cda8b92b3e0f5a15e95baeb.

**Comment by jakubgs** [comment]
Apparently `master` will have that change soon.

**Comment by jakubgs** [comment]
Because of Toledo testnet I made a bunch of changes to layout and build process:
  - https://github.com/status-im/infra-nimbus/commit/b25bd39c
  - https://github.com/status-im/infra-nimbus/commit/5bfaa61b
  - https://github.com/status-im/infra-nimbus/commit/39431c0b
  - https://github.com/status-im/nimbus-eth2/pull/1988
  - https://github.com/status-im/infra-nimbus/commit/dba111b4

**Comment by jakubgs** [comment]
This is already done.
