### ISSUE TITLE
Add eth2stats client to each node

### ISSUE THREAD

**Issue by arnetheduck** [status-im/infra-nimbus#27]
eth2stats allows us to track the nodes on https://pyrmont.eth2.wtf/#/

The instructions for starting the eth2stats client are here: 

https://github.com/protolambda/pyrmont#eth2stats 

with `--eth2stats.node-name="example node"` and `--beacon.type=nimbus` changed, as well as the ports for metrics and RPC.

**Comment by arthurk** [comment]
Is this still something you guys want? The linked pyrmont website looks empty and there is none for Prater. The eth2stats client website shows a 503

**Comment by arnetheduck** [comment]
obsolete - thanks for checking
