### ISSUE TITLE
Deploy a Mainnet fully synced node for Nimbus

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#29]
Eth2 launches on 8th of December and before that happens we'll need a mainnet full node.

It will be used in the future to provide data on state of Eth1 to the Nimbus fleet.

**Comment by jakubgs** [comment]
@zah Just to be sure, do we need a full sync, which is like ~5TB, or would a fast sync - ~500GB - be enough?

**Comment by arnetheduck** [comment]
fast sync is enough

**Comment by jakubgs** [comment]
Changes:

* dfa0f20bdc9c1cd275deae12c4d40fc22c07798b - Node deployment
* 8441dafbbf8805f0dc1c9df963a3cf0b889abaca - Node configuiration

Dashboard:
https://grafana.infra.status.im/d/VyUgFRWZz/geth-syncing?var-fleet=nimbus.geth
