### ISSUE TITLE
Deploy an eth2 mainnet node to be used as bootstrap node

### ISSUE THREAD

**Issue by kdeme** [status-im/infra-nimbus#30]
Deployment of a first eth2 mainnet node, to be used as bootstrap node.

Similar like the pyrmont nodes, but now for the mainnet. To be started as soon as nimbus-eth2 has mainnet support (included the genesis).

It should:
- be build from master
- have no validators attached
- not change ip / ports
- not change network key (which is default arranged already through https://github.com/status-im/infra-role-beacon-node/blob/master/tasks/compose.yml#L42 )

The two last points are I believe already the case for all our pyrmont nodes, I just repeat it here again for clarity as for a bootstrap node it is important these stay the same over time, else the ENR is no longer useful.

**Comment by jakubgs** [comment]
According what I was told by @corpetty which I assume he got form @arnetheduck we want 4 nodes the eth2 mainnet. Correct?

We also apparently need two "bootnodes", not sure what that entails in case of `nimbus-eth`. Is that a separate binary?

What size do we want them? Same as the big ones we use for Pyrmont? Meaning [`z1d.large`](https://aws.amazon.com/ec2/instance-types/z1d/)?

**Comment by arnetheduck** [comment]
for the purpose of this ticket, a bootnode is essentailly a "normal" beacon node without validators attached - like pyrmont, but running mainnet. we should get 2 of those on separate aws instances, `small` will be enough.

the 4 mainnet nodes are a new, separate thing

**Comment by jakubgs** [comment]
Ok, I see, this task is for the initially one and now 2 "bootnodes".

I've made a separate task for the other nodes.

**Comment by jakubgs** [comment]
It was also requested by the powers that be to create all of this Eth2 infra on a separate AWS account.

**Comment by arnetheduck** [comment]
our 2 bootnodes, is it a big difference if we put them in separate data centers?

**Comment by jakubgs** [comment]
It does, because every new datacenter requires a Consul cluster to manage hosts, and without that Consul cluster many things won't work, like for example our internal Tinc VPN. And rolling out a Consul cluster for one host is a bit of an overkill.

But if it's really important we can add another Consul cluster.

**Comment by arnetheduck** [comment]
alright, let's not, for now

**Comment by jakubgs** [comment]
Here are the new nodes:

* [`master-small-01.aws-eu-central-1a.nimbus.mainnet`](https://consul.infra.status.im/ui/aws-eu-central-1a/nodes/master-small-01.aws-eu-central-1a.nimbus.mainnet) - `3.123.252.239`
* [`master-small-02.aws-eu-central-1a.nimbus.mainnet](https://consul.infra.status.im/ui/aws-eu-central-1a/nodes/master-small-02.aws-eu-central-1a.nimbus.mainnet) - `52.59.124.142`

Change: https://github.com/status-im/infra-nimbus/commit/43e8379a

**Comment by jakubgs** [comment]
Updated valid network names: https://github.com/status-im/infra-role-beacon-node/commit/fbfb2169
Deployed mainnet nodes: https://github.com/status-im/infra-nimbus/commit/eb44131d

The look good:
```
 > ansible nimbus-mainnet-small --become-user admin -a 'docker ps'
master-small-02.aws-eu-central-1a.nimbus.mainnet | CHANGED | rc=0 >>
CONTAINER ID        NAMES                              IMAGE                                        CREATED              STATUS
e25ec9b23e67        beacon-node-mainnet-master-small   statusteam/nimbus_beacon_node:master-small   About a minute ago   Up About a minute
master-small-01.aws-eu-central-1a.nimbus.mainnet | CHANGED | rc=0 >>
CONTAINER ID        NAMES                              IMAGE                                        CREATED              STATUS
02ce9e9ea65c        beacon-node-mainnet-master-small   statusteam/nimbus_beacon_node:master-small   About a minute ago   Up About a minute
```

**Comment by jakubgs** [comment]
@kdeme are we good? Do you need anything else for this fleet or can we close this?

**Comment by kdeme** [comment]
@jakubgs All good. Thanks!
