### ISSUE TITLE
Set prometheus and grafana to collect at 12s intervals

### ISSUE THREAD

**Issue by arnetheduck** [status-im/infra-nimbus#31]
In eth2, things happen at a 12s cadence, so it makes sense that monitoring tools poll once every 12s, instead of the default 15s - this should make the graphs line up better with fewer spikes / irregularities that are caused by lack of timing sympathy.

**Comment by stefantalpalaru** [comment]
Remember to match this sampling rate in Grafana's datasource config ("scrape interval" field). It's important for allowing some global vars to work correctly.

**Comment by arnetheduck** [comment]
I guess the argument for a higher granularity would be peer / mem tracking but then it still would make sense to use multiples and divisors of 12

**Comment by arnetheduck** [comment]
actually - 6s might be better - @jakubgs is this doable?

**Comment by jakubgs** [comment]
I'm sure it's doable, but considering how unresponsive and barely usable the Beacon node dashboard already is adding more data points will make it even worse. But sure, lets do it.

**Comment by jakubgs** [comment]
The metrics are collected due to this config:
https://github.com/status-im/infra-hq/blob/1ce12670/ansible/roles/prometheus-slave/templates/prometheus.yml.j2#L93-L99

**Comment by jakubgs** [comment]
It should be as simple as adding a `scrape_interval` to that job definition:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Comment by jakubgs** [comment]
Deployed in: https://github.com/status-im/infra-hq/commit/20e0e333

Seems to be working fine, at least on the scraping side:
![image](https://user-images.githubusercontent.com/2212681/106597691-0aa3d000-6557-11eb-84b0-b7a430d4df23.png)

One host is not responding because I rebuilt `libp2p` locally without `-d:insecure`.

**Comment by jakubgs** [comment]
I'll leave adjusting the dashboard to @stefantalpalaru since he seems to be managing that.

**Comment by stefantalpalaru** [comment]
It's not the dashboard that needs adjusting, but the data source in the Grafana configuration and I don't have access to that for metrics.status.im.

**Comment by jakubgs** [comment]
Okay, then done:
![image](https://user-images.githubusercontent.com/2212681/106648380-7d7d6d00-6590-11eb-996e-c207c5eff532.png)

**Comment by jakubgs** [comment]
Looks like this caused our Prometheus + Cortex setup to choke:
https://user-images.githubusercontent.com/2212681/107016515-52686880-679e-11eb-87f2-0765e487dc6a.png

I'm reverting the change for now.

**Comment by jakubgs** [comment]
I did some tuning of Prometheus in https://github.com/status-im/infra-hq/commit/61f523c1, so I'm trying to lower the scrape interval from default 30 seconds to 15. We'll see that that kills it again. Then we can try going lower.

**Comment by stefantalpalaru** [comment]
Don't forget to change the data source config in Grafana.

**Comment by jakubgs** [comment]
There were some dropped samples but it looks fine now:

![image](https://user-images.githubusercontent.com/2212681/108247023-6a52cb80-7152-11eb-8ab4-5bd39bb4f7b5.png)

And a small spike in pending samples, but it returned to normal:

![image](https://user-images.githubusercontent.com/2212681/108247071-7a6aab00-7152-11eb-991b-e29fb6075ac0.png)

**Comment by jakubgs** [comment]
The number of samples cortex gets went up but the latency looks fine.

![image](https://user-images.githubusercontent.com/2212681/108247189-a128e180-7152-11eb-9ee2-54798e3184a3.png)

Most importantly flush queue looks good:

![image](https://user-images.githubusercontent.com/2212681/108247286-ba319280-7152-11eb-9be6-fd054e4e1e46.png)

I'll let it go for the night and try lower scrape interval tomorrow.

**Comment by jakubgs** [comment]
@stefantalpalaru I don't know if it makes sense to change the scrape interval in the config for the whole source if we just changed it for one specific service. Not really sure what it affects in terms of graphs and how it would impact those that are still using 30s scrape interval.

**Comment by stefantalpalaru** [comment]
This is why it's important for Grafana to know its Prometheus source's sampling rate: https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

**Comment by jakubgs** [comment]
I see.

I went down to 12s interval, looking fine so far:

![image](https://user-images.githubusercontent.com/2212681/108540443-7de06c80-72e1-11eb-8642-d9dd57224a3f.png)

**Comment by jakubgs** [comment]
I tried going from 12 seconds to 6 seconds scrape interval again and it just fails so I reverted it:

![image](https://user-images.githubusercontent.com/2212681/108864188-3fed8c00-75f2-11eb-88fe-801483821fa1.png)

Prometheus was getting 400s and 500s from Cortex and failing to push samples:

![image](https://user-images.githubusercontent.com/2212681/108864269-51cf2f00-75f2-11eb-8e47-d764ad90ea98.png)

**Comment by jakubgs** [comment]
Seems like `master-01` was the only mostly returning 400s and 500s later:

![image](https://user-images.githubusercontent.com/2212681/108864698-bd190100-75f2-11eb-95d4-a524b0cbfb32.png)

**Comment by jakubgs** [comment]
It seems like tha main culprits are `attached_validator_balance` and `attached_validator_balance_created`:
```
admin@master-01.do-ams3.metrics.hq:~ % sudo journalctl --since '1 hour ago' -a -u cortex | awk '/nimbus.pyrmont/{match($0, /__name__=\\"([^"]+)\\"/, r); a[r[1]]++}END{for(x in a){printf "%5d - %s\n", a[x], x}}' | sort -h | tail
    7 - netdata_services_throttle_io_read_KiB_persec_average
    7 - nim_gc_mem_bytes
    7 - process_start_time_seconds
    8 - libp2p_pubsub_received_ihave_created
    8 - netdata_apps_mem_MiB_average
    8 - process_resident_memory_bytes
   11 - process_virtual_memory_bytes
   15 - process_cpu_seconds_total
  688 - attached_validator_balance_created
  690 - attached_validator_balance
```

**Comment by jakubgs** [comment]
Which would suggest to me that the code that returns values for validator balances don't return new values frequently enough, or something like that.

**Comment by jakubgs** [comment]
Well whatever, for now I made it 12 seconds(https://github.com/status-im/infra-hq/commit/001841f6) and I'm gonna leave it at that for now.

**Comment by arnetheduck** [comment]
cc @jakubgs what's the current setting, and does it match the grafana configuration? if yes, we could close this I believe?

**Comment by jakubgs** [comment]
The current setting is 12 seconds:
```yaml
{{ job('beacon-node-metrics', interval='12s') }}
```
https://github.com/status-im/infra-hq/blob/3168e286e417afad19f73c46dd7bff9e464a0455/ansible/roles/prometheus-slave/templates/prometheus.yml.j2#L71

And it is changed on `metrics.status.im`, but not on `grafana.status.im`, because that's mostly not using 12s intervals:

![image](https://user-images.githubusercontent.com/2212681/155296930-fd764e3f-75cd-4d38-b021-7ca296324f57.png)
