### ISSUE TITLE
Have nimbus bootstrap nodes run with subscribe-all-subnets

### ISSUE THREAD

**Issue by kdeme** [status-im/infra-nimbus#38]
The next release (current unstable branch) will introduce a feature to subscribe the node to all subnets, which means it will practically subscribe to all eth2 gossipsub topics. 

We could/should make our bootnodes turn this feature on, so that they are nodes which are most interesting to connect to also after syncing or for discovery reasons.

To enable you need to pass `--subscribe-all-subnets:true` on cli.

**Comment by kdeme** [comment]
@jakubgs Is this something you could add? We basically want _only_ the two bootstrap nodes on mainnet started with the cli option `--subscribe-all-subnets:true`

**Comment by jakubgs** [comment]
Are you referring to the two nodes here:
https://github.com/status-im/infra-nimbus/blob/d88c8b44fcedeb59b1bea3b4bb444bd4ae7b3a66/mainnet.tf#L2-L9
Meaning:
https://github.com/status-im/infra-nimbus/blob/d88c8b44fcedeb59b1bea3b4bb444bd4ae7b3a66/ansible/inventory/test#L73-L75
Because if so then it's fairly easy.

**Comment by jakubgs** [comment]
Took the opportunity to convert the Docker Compose file to a template: https://github.com/status-im/infra-role-beacon-node/commit/691c1347

Added `--subscribe-all-subnets` support via `beacon_node_subscribe_all` in: https://github.com/status-im/infra-role-beacon-node/commit/d8a3cd98

Change as deployed in: https://github.com/status-im/infra-nimbus/commit/a0b0fa87BC
```
admin@stable-small-01.aws-eu-central-1a.nimbus.mainnet:~ % d inspect beacon-node-mainnet-stable-small | jq '.[].Config.Cmd'
[
  "--network=mainnet",
  "--data-dir=/data/shared_mainnet_0",
  "--web3-url=wss://mainnet.infura.io/ws/v3/9e2f2cc13f70432f8b87dbe7d51b81db",
  "--nat=extip:3.120.104.18",
  "--log-level=DEBUG",
  "--tcp-port=9100",
  "--udp-port=9100",
  "--netkey-file=/data/netkey",
  "--slashing-db-kind=v2",
  "--insecure-netkey-password=true",
  "--subscribe-all-subnets=true",
  "--rpc",
  "--rpc-address=0.0.0.0",
  "--rpc-port=11000",
  "--metrics",
  "--metrics-address=0.0.0.0",
  "--metrics-port=9300"
]
```
