### ISSUE TITLE
New `prater` testnet launching

### ISSUE THREAD

**Issue by arnetheduck** [status-im/infra-nimbus#41]
There's a new 200k validator testnet being discussed at the eth2 dev call, named [prater](https://github.com/eth2-clients/eth2-testnets/pull/40) - we will need a new infra setup for this akin to the one for pyrmont - this setup will eventually replace pyrmont but the timeline is not yet certain. 

We will receive a total of 40k validators to manage (vs the 20k we have on Pyrmont today).

This might be a good time to investigate cheaper alternatives to AWS or alternative node types on AWS.

**Comment by arnetheduck** [comment]
@jakubgs there's a launch date now: 23-Mar-2021 02:00:00 PM +UTC

**Comment by jakubgs** [comment]
I'm assigning this to Arthur. He will reach out to you and others in the team to discuss in more detail the requirements for this fleet.

**Comment by mratsim** [comment]
In terms of providers I've identified netcup and Hertzer for cheap dedicated server:

- https://www.netcup.eu/vserver/
- https://www.hetzner.com/dedicated-rootserver

Tentative requirements (unsure about the disk size)

- IO
  - the biggest bottleneck especially if we run Geth + Nimbus.
  - SSD at minimum, NVMe preferred
- CPU
  - 2 or 3  cores minimum, 1 for Nimbus, 1 for Geth, 1 for the rest.
  - Ryzen or Broadwell at minimum (for specific ADX and MULX instruction support),
  - SHA-NI is a plus (Ryzen)
- Memory
  - 2GB minimum for the normal operations
  - 4GB at minimum during compiling
- Disk space (TODO)
  - Geth state (?)
  - Nimbus state (?)
  - logs (?)

**Comment by arnetheduck** [comment]
> Geth

we need two geth instances: mainnet and goerli - they can be shared between the whole fleet, no need to include them in individual servers

**Comment by jlokier** [comment]
Nice list.  Some additional thoughts if they were my validators:

- CPU
  - If the cores are fast enough you don't need as many, but 2-3+ still seems sensible.
  - It's unlikely we'd max out NVMe I/O, but if we did, heavily scattered I/Os like in Eth (high IOPS) use extra CPU.
  - Is the storage sensitive? If so, consider encrypting it, and this will use extra CPU.
  - Virtualised cores (like most AWS) will have more inconsistent performance than dedicated. Not sure how much this matters to the validator network.
  - I am surprised SHA-NI is secondary compared with ADX+MULX, and SHA might increase in importance in future changes to the Merkle tree, but it also might not.

- Memory
  - ECC RAM (Hetzner has this in the AX and PX lines, but you have to request it for some AX).
  - Memory required is probably underestimated if they must run continuously and you also do other things on the server.

- Disk space
  - According to [The Nimbus Beacon Chain Book| System requirements (recommended)](https://nimbus.guide/hardware.html), Geth state is on the order of 290GB, but it's ever changing.

- Availability
  - Not sure if it's important to the testnet, but dedicated servers occasionally (rarely) fail and it takes some time to replace parts, so you might want at least one other as backup.
  - For 20k validators, multiple cheaper machines may be more sensible than one expensive one.

**Comment by kdeme** [comment]
@arnetheduck Differently from pyrmont, shall we have some non validator nodes as bootstrap? Or we use (some of) the validators nodes also as bootstrap nodes like it is done now for pyrmont?

**Comment by arthurk** [comment]
Summary from discussion in discord:

- We will use the same AWS infra for now because the deadline is close and we don't have time to switch to a new provider
- Long-term we want to switch to Hetzner, mainly because of cost savings
- Requirements are 16 z1d.large AWS instances, each running 2500 validators. There will be no split between large/small instances like for pyrmont
- The cost is around 3300 USD per month. Request to finance team has been sent

One more thing I need to know is how many hosts should run for each branch (stable, testing, unstable)

**Comment by q9f** [comment]
Just want to comment that Hetzner is very reliable and if you know what server spec you need (roughly) you can rent used dedicated hardware way cheaper on the "Serverbörse" https://www.hetzner.com/sb - which is potentially fine for any testnet deployment.

**Comment by jakubgs** [comment]
Arthur has deployed hosts for the Prater testnet after merging #44:
```
 > ansible localhost -m debug -a 'var=groups["nimbus.prater"]'
localhost | SUCCESS => {
    "groups[\"nimbus.prater\"]": [
        "libp2p-large-01.aws-eu-central-1a.nimbus.prater",
        "stable-large-01.aws-eu-central-1a.nimbus.prater",
        "stable-large-02.aws-eu-central-1a.nimbus.prater",
        "stable-large-03.aws-eu-central-1a.nimbus.prater",
        "stable-large-04.aws-eu-central-1a.nimbus.prater",
        "stable-large-05.aws-eu-central-1a.nimbus.prater",
        "testing-large-01.aws-eu-central-1a.nimbus.prater",
        "testing-large-02.aws-eu-central-1a.nimbus.prater",
        "testing-large-03.aws-eu-central-1a.nimbus.prater",
        "testing-large-04.aws-eu-central-1a.nimbus.prater",
        "testing-large-05.aws-eu-central-1a.nimbus.prater",
        "unstable-large-01.aws-eu-central-1a.nimbus.prater",
        "unstable-large-02.aws-eu-central-1a.nimbus.prater",
        "unstable-large-03.aws-eu-central-1a.nimbus.prater",
        "unstable-large-04.aws-eu-central-1a.nimbus.prater",
        "unstable-large-05.aws-eu-central-1a.nimbus.prater"
    ]
}
```
Updated the inventory: https://github.com/status-im/infra-nimbus/commit/ff48a961

He will deploy the nodes tomorrow.

**Comment by jakubgs** [comment]
@arthurk I have deployed first two stable nodes because @zah needed them as bootstrap nodes for the testnet:
```
 > ansible-playbook ansible/prater.yml -l stable-large-01.aws-eu-central-1a.nimbus.prater,stable-large-02.aws-eu-central-1a.nimbus.prater

...

PLAY RECAP ***********************************************************************************************************************************************
stable-large-01.aws-eu-central-1a.nimbus.prater : ok=15   changed=8    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
stable-large-02.aws-eu-central-1a.nimbus.prater : ok=15   changed=8    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 
```
This shouldn't change what you have to do tomorrow, just noting it down so you're not surprised. I haven't deployed the validators.

**Comment by arthurk** [comment]
Nodes are up and running. The public grafana dashboard needs to be modified to allow the new nodes which was done in https://github.com/status-im/infra-hq/commit/a6668c7f95986755e6e16b6459148b286222a002

**Comment by arthurk** [comment]
The Bootnodes needed additional adjustments in https://github.com/status-im/infra-nimbus/commit/2088c0c92b494abab4475f19d760eb47b18a8138:

- Beacon node role has been updated to support `--max-peers` https://github.com/status-im/infra-role-beacon-node/commit/4f04bd279b09bc768bb4afdb9a4ac3a1b3c4ae4f
- `--subscribe-all-subnets` has been enabled

**Comment by arthurk** [comment]
max-peers has been set to 320 on all nodes https://github.com/status-im/infra-nimbus/commit/b03dbdb5c6ccd0f041a29b328782056d9508d3e1

**Comment by jakubgs** [comment]
The genesis worked, but with a 13 minute delay due to doppelganger prevention: https://github.com/status-im/nimbus-eth2/issues/2451

We started sending attestations only after first 2 epochs, because the genesis edge case is not covered:
![image](https://user-images.githubusercontent.com/2212681/112163576-74eaff80-8bed-11eb-8a3b-b299ee4b8899.png)

First proposed block: https://prater.beaconcha.in/block/65

Other than that this appears to be a success.
The next step would be to migrate to some cheaper hardware hosts, which is covered by https://github.com/status-im/infra-nimbus/issues/45.
