### ISSUE TITLE
Date-stamp log files

### ISSUE THREAD

**Issue by arnetheduck** [status-im/infra-nimbus#42]
Currently, log files are called docker.1 etc - this is a bit annoying because every hour, all logfiles are renamed and it's a bit messy to correlate an event in metrics with the corresponding log file.

Date-stamped files instead would be nice, UTC ideally so that it's easy to cross-reference.

**Comment by arnetheduck** [comment]
https://nimbus.guide/log-rotate.html#using-rotatelogs shows an example of how to do this - would need adjusting for json

**Comment by arthurk** [comment]
We could enable this for all servers since we use the same logrotate config, what do you think @jakubgs ?

**Comment by jakubgs** [comment]
I don't want any more tools. We use Rsyslog with Logrotate, and unless there is no way to do timestamps using Logrotate I see no reason to introduce new tools. @arthurk can you look into using timestamps instead of numbers?

**Comment by arthurk** [comment]
logrotate has an option `dateext` that is easy to use. just wanted to know if we only enable this for infra-nimbus or for all servers?

**Comment by jakubgs** [comment]
Sure, timestamps are just a good thing in general.

**Comment by arthurk** [comment]
I've changed the logrotate config on libp2p-unstable, waiting now for the next rotation to happen

**Comment by jakubgs** [comment]
Are we perhaps rotating a bit too frequently by size?
```
admin@u-libp2p-u-large-01.aws-eu-central-1a.nimbus.prater:/var/log/docker/beacon-node-prater-unstable-libp2p-unstable-large % ls -l | head -n20
total 3705992
-rw-r--r-- 1 syslog adm 590860467 Apr 21 08:42 docker.log
-rw-r--r-- 1 syslog adm  58416245 Apr 20 08:00 docker.log-2021042008.gz
-rw-r--r-- 1 syslog adm  51949407 Apr 20 09:00 docker.log-2021042009.gz
-rw-r--r-- 1 syslog adm  52333884 Apr 20 10:00 docker.log-2021042010.gz
-rw-r--r-- 1 syslog adm  51043085 Apr 20 11:00 docker.log-2021042011.gz
-rw-r--r-- 1 syslog adm  52019142 Apr 20 12:00 docker.log-2021042012.gz
-rw-r--r-- 1 syslog adm  55198038 Apr 20 13:00 docker.log-2021042013.gz
-rw-r--r-- 1 syslog adm  58285305 Apr 20 14:00 docker.log-2021042014.gz
-rw-r--r-- 1 syslog adm  55640370 Apr 20 15:00 docker.log-2021042015.gz
-rw-r--r-- 1 syslog adm  49202648 Apr 20 16:00 docker.log-2021042016.gz
-rw-r--r-- 1 syslog adm  51589876 Apr 20 17:00 docker.log-2021042017.gz
-rw-r--r-- 1 syslog adm  44817806 Apr 20 18:00 docker.log-2021042018.gz
-rw-r--r-- 1 syslog adm  50708472 Apr 20 19:00 docker.log-2021042019.gz
-rw-r--r-- 1 syslog adm  54323210 Apr 20 20:00 docker.log-2021042020.gz
-rw-r--r-- 1 syslog adm  54368575 Apr 20 21:00 docker.log-2021042021.gz
-rw-r--r-- 1 syslog adm  56560275 Apr 20 22:00 docker.log-2021042022.gz
-rw-r--r-- 1 syslog adm  48223254 Apr 20 23:00 docker.log-2021042023.gz
-rw-r--r-- 1 syslog adm  46475488 Apr 21 00:00 docker.log-2021042100.gz
-rw-r--r-- 1 syslog adm  49913465 Apr 21 01:00 docker.log-2021042101.gz
```

**Comment by jakubgs** [comment]
Ah, it's hourly:
```
admin@u-libp2p-u-large-01.aws-eu-central-1a.nimbus.prater:~ % cat /etc/logrotate.d/docker                                                    
/docker/log/*/docker.log
{
    rotate 72
    maxsize 500M
    hourly
    missingok
    notifempty
    delaycompress
    copytruncate
    compress
    dateext
}
```
Ah well. We did that for some good reason I'm sure.

**Comment by arnetheduck** [comment]
50 mb is a convenient size though, ie something `vi` can swallow without too much trouble

**Comment by jakubgs** [comment]
@arnetheduck well, `vi` can handle multi-GB files just fine if you turn of syntax highlighting.

**Comment by arnetheduck** [comment]
as if I knew how to do that...

besides, it's `gz`, so it's more like 500mb that has to be decompressed on the fly etc.

the other reason is that I occasionally copy it to local when things get trickier, and again, 50mb is a good scp size

**Comment by jakubgs** [comment]
@arnetheduck You can pass settings with `-c`:
```
vi -c 'syntax off' ${FILE}
```

**Comment by arthurk** [comment]
change has been committed to our bootstrap role and will be rolled out on all servers soon

**Comment by arthurk** [comment]
one more thing, we need to cleanup the old log files after a few days. once the logrotate config is changed it won't clean up files with the old name like `docker.log.1.gz`

**Comment by jakubgs** [comment]
Yeah, we should purge all of those when changing the config.
What I usually do is modify the ansible role that does the config change to also do the cleanup if it's complex.

If it's not I just run a shell comand via `ansible`.

**Comment by arnetheduck** [comment]
not sure what's left to do here, but I'm very happy with what's been done ;)

**Comment by jakubgs** [comment]
I think we should deploy this change to all hosts, and this issue can track that.
Arthur is out today, but hopefully he'll get to that tomorrow.

**Comment by arthurk** [comment]
Changes are rolled out on all hosts. Will work on the cleanup next

**Comment by jakubgs** [comment]
@arthurk did you finish the cleanup? Can this be closed?

**Comment by jakubgs** [comment]
I see there's no update on this so I've done the cleanup myself with this:
```
ansible all -a "find /var/log/docker -regex '.*/docker.log.[0-9]+\(.gz\)?$' -exec rm {} \;"
```
And went though all infra repos and ran this. I consider this closed.
