### ISSUE TITLE
Provision a new large node for the Steklo (Rayonism) testnet

### ISSUE THREAD

**Issue by zah** [status-im/infra-nimbus#53]
This node will participate in the first testnet aiming to experiment with the upcoming Eth1+Eth2 merge functionality. The node needs to be provisioned with the following roles:

* infra-role-beacon-node
* infra-role-geth

The Geth node will need to use a recent version of Geth (compiled from the `master` branch). It needs to be launched with a new special flag (`--catalyst`) that enables the merge spec. It should also allow overriding the the `--miner.etherbase` flag. Since the merge spec requires a fresh network, the storage requirements will be low and there will be no syncing.

The beacon node will use a new docker tag, called `rayonism`. It will be initially built from the `quick-merge-v1 ` branch in nimbus-eth2. The `--network` parameter will be set to `steklo`. The node will run 2048 validators that will be pushed later today or tomorrow to `nimbus-private/steklo_validators`.

**Comment by tersec** [comment]
`--catalyst` is the flag name. Example at https://github.com/status-im/nimbus-eth2/blob/quick-merge-v1/scripts/run-catalyst.sh

**Comment by zah** [comment]
Initially, there won't be any bootstrap nodes for the Geth network, so we can run with `--nodiscover` for best results.

**Comment by jakubgs** [comment]
The latest Geth image is at `871f50b9115976d127aaf4b8a53d9b64259e2fa0`:
```
 > d run --rm -it ethereum/client-go:latest version               
Geth
Version: 1.10.3-unstable
Git Commit: 871f50b9115976d127aaf4b8a53d9b64259e2fa0
Git Commit Date: 20210429
```
Which is newer than the `1fb9a6dd32b581c912d672634882d7e2eb2775cd` that @tersec tested.

**Comment by jakubgs** [comment]
Deployed `qmerge-large-01.aws-eu-central-1a.nimbus.steklo` in https://github.com/status-im/infra-nimbus/commit/8edfb874.

**Comment by jakubgs** [comment]
Since the "Rayonism" project will involve multiple short-lived testnets I decided to rename the host to:
```
qmerge-large-01.aws-eu-central-1a.nimbus.rayonism
```
So we can reuse it for different testnets, or even run multiple at the same time to avoid extra costs and work.

Re-pushed change: https://github.com/status-im/infra-nimbus/commit/ba864487

**Comment by jakubgs** [comment]
With `light` sync mode enabled I got this:
```
Fatal: Catalyst does not work in light client mode.
```
But with `snap` sync mode I got this:
```
Fatal: Error starting protocol stack: invalid peer config: light peer count (100) >= total peer count (0)
```

**Comment by jakubgs** [comment]
With `--light.maxpeers=0` I got:
```
Fatal: Error starting protocol stack: invalid peer config: light peer count (0) >= total peer count (0)
```
So I used `--light.maxpeers=-1` and it worked.

**Comment by jakubgs** [comment]
I've deployed the Geth node using the [genesis config file](https://github.com/protolambda/steklo/blob/master/eth1_config.json):
```
admin@qmerge-large-01.aws-eu-central-1a.nimbus.rayonism:/docker % d
CONTAINER ID   NAMES                IMAGE                CREATED          STATUS
1c593d4cc41a   nimbus-steklo-node   ethereum/client-go   19 seconds ago   Up 18 seconds
```
Changes:

- https://github.com/status-im/infra-role-geth/commit/27ff1d25 - support running init before container creation
- https://github.com/status-im/infra-role-geth/commit/8d2eeb89 - add support for geth_extra_flags list
- https://github.com/status-im/infra-nimbus/commit/1ce2b2c7 - rayonism: deploy Geth node for steklo testnet

**Comment by jakubgs** [comment]
Added builds for `quick-merge-v1` branch in https://github.com/status-im/infra-nimbus/commit/6b8245ad:
```
admin@testing-large-01.aws-eu-central-1a.nimbus.pyrmont:~ % sudo systemctl list-timers 'beacon-node-build-qmerge-large' 
NEXT                        LEFT     LAST PASSED UNIT                                 ACTIVATES                             
Fri 2021-04-30 04:00:00 UTC 15h left n/a  n/a    beacon-node-build-qmerge-large.timer beacon-node-build-qmerge-large.service
```

**Comment by jakubgs** [comment]
Okay, the image has finished baking:
```
admin@testing-large-01.aws-eu-central-1a.nimbus.pyrmont:~ % s beacon-node-build-qmerge-large.service
● beacon-node-build-qmerge-large.service - Docker image build for Nimbus beacon node
     Loaded: loaded (/etc/systemd/system/beacon-node-build-qmerge-large.service; disabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2021-04-29 13:10:31 UTC; 46s ago
TriggeredBy: ● beacon-node-build-qmerge-large.timer
       Docs: https://github.com/status-im/infra-role-systemd-timer
    Process: 1926600 ExecStart=/data/beacon-node-builds/qmerge-large/build.sh (code=exited, status=0/SUCCESS)
   Main PID: 1926600 (code=exited, status=0/SUCCESS)

build.sh[1939636]: db551544340a: Pushed
build.sh[1939636]: qmerge-large: digest: sha256:2a539e4d69b9462750e08923fa17619f47f53ebf4e99439066ddcbaffd333
build.sh[1926600]: SUCCESS - pushed: statusteam/nimbus_beacon_node:qmerge-large
systemd[1]: beacon-node-build-qmerge-large.service: Succeeded.
systemd[1]: Finished Docker image build for Nimbus beacon node.
```
And the node has been deployed, but it appears to not recognize the network name:
```
{"lvl":"FAT","ts":"2021-04-29 13:15:13.089+00:00","msg":"Unrecognized network name","tid":1,"file":"network_metadata.nim:220","networkName":"steklo"}
```
Change: https://github.com/status-im/infra-nimbus/commit/d6795925

**Comment by zah** [comment]
The latest version of the `nimbus-eth2` code in the `quick-merge-v1` branch should resolve the "Unrecognized network name" error.

**Comment by jakubgs** [comment]
Fixed the error:
```json
{
  "jsonrpc": "2.0",
  "id": 42,
  "error": {
    "code": -32601,
    "message": "the method consensus_newBlock does not exist/is not available"
  }
}
```
By adding `consensus` to the `--http.api` flag: https://github.com/status-im/infra-nimbus/commit/1b54f4e1

**Comment by jakubgs** [comment]
Looks like the Nimbus node was in a restart loop due to protocol/port mismatch:
```
Error: unhandled exception: Trying to access value with err Result: Failed to setup web3 connection [ResultDefect]
```
Fixed by using `http://` instead of `ws://`: https://github.com/status-im/infra-nimbus/commit/518726e5

**Comment by jakubgs** [comment]
Also set `debug` log level for Geth node: https://github.com/status-im/infra-nimbus/commit/6d832ae5

**Comment by jakubgs** [comment]
Heh, we forgot to deploy the validators: https://github.com/status-im/infra-nimbus/commit/02b70ee6

**Comment by jakubgs** [comment]
There was an issue with Nimbus node not being able to access the Geth node, mostly because they were two separate compose setups that used different networks. I fixed this temporarily by copying over the `geth` container definition into the Nimbus node one and using `geth` as address for eth1 sync endpoint.

We can do the same thing with ansible, but will require some refactoring. I can do that on Wednesday.

**Comment by jakubgs** [comment]
I consider this done.
