### ISSUE TITLE
Introduce Windows and macOS hosts to the Nimbus fleet

### ISSUE THREAD

**Issue by zah** [status-im/infra-nimbus#58]
Nimbus strives to officially support Linux, Windows and macOS in both 32-bit and 64-bit builds for x86 and ARM. Unfortunately, at the moment, we are testing adequately only one specific build configuration on our Pyrmon and Prater testnet fleets (Linux, 64-bit, x86 aka AMD64). The goal of this task is to introduce additional Windows and macOS hosts to the fleet that will allow us to detect potential problems on these operating systems.

We need to select a cloud provider for a single Windows server and a single macOS server. The minimum hardware requirements for both hosts are as follows:

* at least 4-core CPU
* at least 8 GB of RAM
* NVMe SSD Disk

Preferably, the macOS host should be the new mac mini M1.

Each host will run 3 instances of `infra-role-beacon-node` connected to the Prater testnet. Each instance will run a build from a different branch (unstable, testing, stable). The Windows servers will take over the validators of the current Prater testnet assigned to index 03 (e.g. stable-03, testing-03, etc). The macOS will take the validators currently assigned to index 04.

On the Windows server, the `nimbus_beacon_node.exe` executable will be launched as a service through the 
https://github.com/winsw/winsw utility.

Both hosts will feature an update script that builds the binaries from source from the latest revision of the respective git branch. The update script should be executable on-demand and also automatically once per day through a scheduled task. The node should be restarted only if the latest git revision has changed. The nimbus-private repo should be updated with some minimal instructions for executing the update script manually and for inspecting the log output of the automated runs.

### Tasks

* [x] https://github.com/status-im/infra-nimbus/issues/59 - Deploy Beacon Node on Windows
* [x] https://github.com/status-im/infra-nimbus/issues/60 - Deploy Beacon Node on MacOS

**Comment by jakubgs** [comment]
I consider this done.
