### ISSUE TITLE
Wipe database of 2 mainnet nodes

### ISSUE THREAD

**Issue by arnetheduck** [status-im/infra-nimbus#86]
Every weekend, we should wipe the database of 2 mainnet nodes and restart them, so as to stress the syncing algorithm, forwards and backwards.

On one of them, we should run [trusted node sync](https://nimbus.guide/trusted-node-sync.html) without backfill before restartin:

```
build/nimbus_beacon_node trustedNodeSync --network:mainnet \
 --data-dir=build/data/shared_mainnet_0 \
 --trusted-node-url=http://localhost:XXXX \
 --backfill:false
```

**Comment by jakubgs** [comment]
Should those be nodes on the same host or different hosts? Any specific branch?

**Comment by jakubgs** [comment]
Also, should the trusted sync node be from the same host just different branch? Or same branch from different host?

**Comment by jakubgs** [comment]
Another question: do all nodes have the ability to allow trusted node sync by default? Or is there a flag for it?

And if there is, what API endpoint can I call to check if it is enabled on the node?

**Comment by jakubgs** [comment]
Another question. Can you give me a very rough of how long this `trustedNodeSync` should last if it just happens between nodes on the same host. I need to give the timer some kind of timeout, but it needs to be long enough, while still useful.

**Comment by arnetheduck** [comment]
> Should those be nodes on the same host or different hosts? Any specific branch?

can use `unstable` for this - metal-06 is as good as any

> Also, should the trusted sync node be from the same host just different branch? Or same branch from different host?

same host, but sync against `testing` (can't sync against a wiped node)

> Another question: do all nodes have the ability to allow trusted node sync by default? Or is there a flag for it?

It uses the `--rest` api, nothing special needed

> how long t

up to a few minutes - 5 is a good timeout

**Comment by arnetheduck** [comment]
indeed, it syncs a recent state, then the rest is filled in as the node runs
