### ISSUE TITLE
Deploy initial Fluffy testnet fleet

### ISSUE THREAD

**Issue by kdeme** [status-im/infra-nimbus#87]
In the near future (exact dates undefined) cross client public testnets will be started for the Portal Network.
This issue is about having already our "own testnet fleet" running to get ready on the infrastructure side for when we need to join the public testnet(s). It would allow us developers to test more on a real life scenario also.

At least for the initial tests a Fluffy node will be very light on the resources. We do need however a good amount of nodes running for the testing to be relevant.
I expect  maximum ~2 GB of storage per node for now (this will change for some nodes later on). CPU / memory is a bit more difficult to estimate at the moment, but it should be rather low in comparison with an eth2 or eth1 node.

Because of this it might be cheaper/better to run several nodes on the same machine. Especially if that makes it easier to launch more of them as we see fit.
With the low resources they use, different IPs might be the more costly part? For this reason there is the hidden development option in Fluffy to increase the amount of nodes with the same IP address that are accepted in the routing table (see options further down). This allows us to run many nodes on the same machine with 1 interface/ip.

I was thinking of initially starting with 32 to 64 nodes. Perhaps split over 2 to 4 machines. Then with the possibility of increasing the number of nodes per machine in the future. It depends on the cost, of which I have no good view. But this shouldn't be expensive I would expect. Feel free to suggest different setups. 
Something like 4 of these nodes should be the bootstrap nodes.

### Fluffy build instructions
https://github.com/status-im/nimbus-eth1/tree/master/fluffy#how-to-build--run

### General fluffy options:
```
 ./build/fluffy --help
Usage: 

fluffy [OPTIONS]... command

The following options are available:

 --log-level              Sets the log level [=DEBUG].
 --udp-port               UDP listening port [=9009].
 --listen-address         Listening address for the Discovery v5 traffic [=0.0.0.0].
 --bootstrap-node         ENR URI of node to bootstrap Discovery v5 and the Portal networks from. Argument
                              may be repeated.
 --bootstrap-file         Specifies a line-delimited file of ENR URIs to bootstrap Discovery v5 and Portal
                              networks from.
 --nat                    Specify method to use for determining public address. Must be one of: any, none,
                              upnp, pmp, extip:<IP> [=any].
 --enr-auto-update        Discovery can automatically update its ENR with the IP address and UDP port as
                              seen by other nodes it communicates with. This option allows to enable/disable
                              this functionality [=false].
 --data-dir               The directory where fluffy will store the content data
                              [=~/.cache/fluffy].
 --netkey-file            Source of network (secp256k1) private key file [=config.dataDir / "netkey"].
 --metrics                Enable the metrics server [=false].
 --metrics-address        Listening address of the metrics server [=127.0.0.1].
 --metrics-port           Listening HTTP port of the metrics server [=8008].
 --rpc                    Enable the JSON-RPC server [=false].
 --rpc-port               HTTP port for the JSON-RPC server [=8545].
 --rpc-address            Listening address of the RPC server [=127.0.0.1].
 --bridge-client-uri      if provided, enables getting data from bridge node.
 --proxy-uri              URI of eth client where to proxy unimplemented rpc methods to
                              [=http://127.0.0.1:8546].
 --radius                 Hardcoded (logarithmic) radius for each Portal network. This is a temporary
                              development option which will be replaced in the future by e.g. a storage size
                              limit [=256].
```

### Options that should be configurable in the role

`--log-level` -> default to debug for now
`--udp-port`  -> e.g. when we run several nodes on the same machine
`--nat:extip` -> in case we need to set this
`--data-dir` -> database etc location
`--netkey-file` -> Differently from eth2 nodes, the netkey file should default be stored for all nodes, not just bootstrap nodes. As the data it stores in the database is based on this key and the radius value. However, there is no huge issue with losing it, it will just redownload an other range of data. Except for bootstrap nodes once we would be running in a public testnet. Also, the file is just plaintext at the moment and not yet an encrypted keystore.
`--bootstrap-file` -> We should create a file with the ENRs of the designated bootstrap nodes
`--bootstrap-node` -> or, instead of the file passed as individual arguments
`--table-ip-limit` -> Hidden parameter, can set to 1024 to avoid any ip limiting issues for now
`--bucket-ip-limit` -> Hidden parameter, can set to 24 to avoid any ip limiting issues for now
`--bits-per-hop=1` -> set to 1 default now, later we might play with this value
`--radius=253` -> Should become adjustable, can set to 253 default for now

Metrics and rpc will be definitely be useful to enable later on. And have some dashboard, but it is not a priority for now (we don't really have good metrics yet anyhow).

It would be nice to see some of these nodes running in say two weeks (week of 9 March), if that is feasible.

cc @jakubgs

**Comment by jakubgs** [comment]
Should this be deployed as part of `infra-nimbus` fleet configuration, or sepparately? As `infra-fluffy`?

**Comment by jakubgs** [comment]
I've created a repo for Fluffy node Ansible role: https://github.com/status-im/infra-role-nimbus-fluffy

Change: https://github.com/status-im/infra-repos/commit/22ef213a

**Comment by jakubgs** [comment]
Also:

>We should create a file with the ENRs of the designated bootstrap nodes

What are the "designated bootstrap nodes"?

**Comment by jakubgs** [comment]
I see no network flag. Does it just default to `mainnet` without option to change that?

**Comment by jakubgs** [comment]
Looks like I can use the `` RPC call to get the END address of the node:
```
 > ./rpc.sh discv5_nodeInfo    
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "nodeId": "0x13cbf3f32e5647d4404f52cf900f94e3f478e2fe7a94de3fe4b9ffb3ce431c0f",
    "nodeENR": "enr:-IS4QLasApr5-KIVOSfXKHrcIFHuLfbkk79023u1jpoATWJNBjHRRyZvlA2t-Asg7bLSbgqP0R1HEy1Eft_zzd-dKi8BgmlkgnY0gmlwhEEVxC6Jc2VjcDI1NmsxoQIYkCs9YxQsrZxc6Fc81hq4LHkz1VVfME5wlZ4ymuHvb4N1ZHCCIzE"
  }
}
```

**Comment by jakubgs** [comment]
And here we have the first working version of the role: https://github.com/status-im/infra-role-nimbus-fluffy/commit/7945026dc7c0fab3d0b27e992bd5b3f2638d9f55

**Comment by kdeme** [comment]
> What are the "designated bootstrap nodes"?

Currently there is no actual public / cross client testnet, and no repo (like in eth2) that would store a file with the bootstrap nodes their ENRs per network.

So we would have to provide a file ourselves. Aside from that, the ENR can indeed be requested from a node through the `discv5_nodeInfo` rpc call. The ENR of the node should also be stored in a file in the data folder of that node.

**Comment by jakubgs** [comment]
I've requested a budget increase for two AX41-NVMe Hetzner hosts.

**Comment by jakubgs** [comment]
Added and bootstrapped two new hosts: https://github.com/status-im/infra-nimbus/commit/2a98be3a
https://github.com/status-im/infra-nimbus/blob/2a98be3ade9cc11f371611c6085498f615bf6896/ansible/inventory/test#L89-L91

**Comment by jakubgs** [comment]
It looks like we won't be running any specific branches for a while, so the current setup of the Ansible role that runs a separate build for each node doesn't make sense. I'll need to make it run just one build for all nodes.

But this introduces the question of restarting the nodes, and whether it should be done all at once or staggered.

**Comment by jakubgs** [comment]
According to @kdeme nodes can be restarted all at once without harm, which makes things simple.

**Comment by jakubgs** [comment]
The resource usage from these nodes is tiny:

![image](https://user-images.githubusercontent.com/2212681/157262454-4e4c0e45-cd4a-4495-8aa0-67a31e3d2333.png)

It doesn't seem like they are doing much:
```
admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % tail -n2 logs/service.log
NOT 2022-03-08 13:53:51.186+00:00 Starting metrics HTTP server               url=http://0.0.0.0:9201/metrics
INF 2022-03-08 13:53:51.186+00:00 Starting JSON-RPC HTTP server              topics="JSONRPC-HTTP-SERVER" url=http://127.0.0.1:9901
```
I assume that's because there are no bootstrap nodes defined and they can't connect to anything.

That will be the next step.

**Comment by jakubgs** [comment]
Some more improvements:

- https://github.com/status-im/infra-role-nimbus-fluffy/commit/a97db210 - consul: use rpc.sh and discv5_nodeInfo for check
- https://github.com/status-im/infra-role-nimbus-fluffy/commit/e448cb36 - consul: add ENR address to service metadata
- https://github.com/status-im/infra-nimbus/commit/71a0430e - nimbus.fluffy: add loop_var, include consul fixes

I will probably just pick `01` and `02` as bootstrap nodes tomorrow and use those via CLI flags.

**Comment by jakubgs** [comment]
I picked the first two nodes from each host as bootstrap nodes:
```
 > a nimbus.fluffy --become -a "bash -c 'jq -r \".services[0].meta.node_enr\" /etc/consul/service_nimbus_fluffy_mainnet_master_0{1,2}.json'" 
metal-01.he-eu-hel1.nimbus.fluffy | CHANGED | rc=0 >>
enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40
enr:-IS4QOA4voX3J7-R_x8pjlaxBTpT1S_CL7ZaNjetjZ-0nnr2VaP0wEZsT2KvjA5UWc8vi9I0XvNSd1bjU0GXUjlt7J0BgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQI7aL5dFuHhwbxWD-C1yWH7UPlae5wuV_3WbPylCBwPboN1ZHCCI44
metal-02.he-eu-hel1.nimbus.fluffy | CHANGED | rc=0 >>
enr:-IS4QFzPZ7Cc7BGYSQBlWdkPyep8XASIVlviHbi-ZzcCdvkcE382unsRq8Tb_dYQFNZFWLqhJsJljdgJ7WtWP830Gq0BgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQPjz2Y1Hsa0edvzvn6-OADS3re-FOkSiJSmBB7DVrsAXIN1ZHCCI40
enr:-IS4QHA1PJCdmESyKkQsBmMUhSkRDgwKjwTtPZYMcbMiqCb8I1Xt-Xyh9Nj0yWeIN4S3sOpP9nxI6qCCR1Nf4LjY0IABgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQLMWRNAgXVdGc0Ij9RZCPsIyrrL67eYfE9PPwqwRvmZooN1ZHCCI44
```

**Comment by jakubgs** [comment]
I'm trying to use a bootstrap file:
```
admin@metal-01.he-eu-hel1.nimbus.fluffy:~ % s cat nimbus-fluffy-mainnet-master-01.service | grep bootstrap
  --bootstrap-file=/data/nimbus-fluffy-mainnet-master-01/data/bootstrap \

admin@metal-01.he-eu-hel1.nimbus.fluffy:~ % sudo cat /data/nimbus-fluffy-mainnet-master-01/data/bootstrap
enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40
enr:-IS4QOA4voX3J7-R_x8pjlaxBTpT1S_CL7ZaNjetjZ-0nnr2VaP0wEZsT2KvjA5UWc8vi9I0XvNSd1bjU0GXUjlt7J0BgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQI7aL5dFuHhwbxWD-C1yWH7UPlae5wuV_3WbPylCBwPboN1ZHCCI44
enr:-IS4QFzPZ7Cc7BGYSQBlWdkPyep8XASIVlviHbi-ZzcCdvkcE382unsRq8Tb_dYQFNZFWLqhJsJljdgJ7WtWP830Gq0BgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQPjz2Y1Hsa0edvzvn6-OADS3re-FOkSiJSmBB7DVrsAXIN1ZHCCI40
enr:-IS4QHA1PJCdmESyKkQsBmMUhSkRDgwKjwTtPZYMcbMiqCb8I1Xt-Xyh9Nj0yWeIN4S3sOpP9nxI6qCCR1Nf4LjY0IABgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQLMWRNAgXVdGc0Ij9RZCPsIyrrL67eYfE9PPwqwRvmZooN1ZHCCI44
```
But it fails with:
```
FAT 2022-03-16 10:12:52.424+00:00 Unknown bootstrap file format              ext=
```

**Comment by jakubgs** [comment]
Tried JSON but that fails too:
```
admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % sudo cat /data/nimbus-fluffy-mainnet-master-01/data/bootstrap.json
[
    "enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40",
    "enr:-IS4QOA4voX3J7-R_x8pjlaxBTpT1S_CL7ZaNjetjZ-0nnr2VaP0wEZsT2KvjA5UWc8vi9I0XvNSd1bjU0GXUjlt7J0BgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQI7aL5dFuHhwbxWD-C1yWH7UPlae5wuV_3WbPylCBwPboN1ZHCCI44",
    "enr:-IS4QFzPZ7Cc7BGYSQBlWdkPyep8XASIVlviHbi-ZzcCdvkcE382unsRq8Tb_dYQFNZFWLqhJsJljdgJ7WtWP830Gq0BgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQPjz2Y1Hsa0edvzvn6-OADS3re-FOkSiJSmBB7DVrsAXIN1ZHCCI40",
    "enr:-IS4QHA1PJCdmESyKkQsBmMUhSkRDgwKjwTtPZYMcbMiqCb8I1Xt-Xyh9Nj0yWeIN4S3sOpP9nxI6qCCR1Nf4LjY0IABgmlkgnY0gmlwhEFsKq6Jc2VjcDI1NmsxoQLMWRNAgXVdGc0Ij9RZCPsIyrrL67eYfE9PPwqwRvmZooN1ZHCCI44"
]

admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % tail -n1 logs/service.log                                         
FAT 2022-03-16 10:18:31.174+00:00 Unknown bootstrap file format              ext=.json
```
What is this about?

**Comment by kdeme** [comment]
hmm, looks like there is a silly `*.txt` or `*.enr` file extension check leftover. I guess that is not really needed and could be removed.

**Comment by jakubgs** [comment]
Oh, ok, I can use that extension for now. Thanks.

**Comment by jakubgs** [comment]
This is new:
```
ERR 2022-03-16 10:22:21.987+00:00 Bootstrap node could not be added          topics="portal_wire" uri=enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40 protocolId="[80, 10]"
ERR 2022-03-16 10:22:21.987+00:00 Bootstrap node could not be added          topics="portal_wire" uri=enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40 protocolId="[80, 11]"
ERR 2022-03-16 10:22:30.988+00:00 Bootstrap node could not be added          topics="portal_wire" uri=enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40 protocolId="[80, 10]"
```

**Comment by jakubgs** [comment]
This is a cool tool for looking up contents of ENR records: https://enr-viewer.com/

![image](https://user-images.githubusercontent.com/2212681/158570316-6778645a-a8de-419f-aedc-857e18a15e42.png)

There's also `record print` sub-command for `nimbus_beacon_node`:
```
 > nimbus_beacon_node record print --help
Nimbus beacon node v22.3.0-13b264-stateofus

Usage: 

nimbus_beacon_node_13b264d5 record print <enr>

Print the content of a given ENR.

 <enr>        ENR URI of the record to print.

 > nimbus_beacon_node record print enr:-IS4QGeTMHteRmm-MSYniUd48OZ1M7RMUsIjnSP_TRbo-goQZAdYuqY2PyNJfDJQBz33kv16k7WB3bZnBK-O1DagvJIBgmlkgnY0gmlwhEFsKgOJc2VjcDI1NmsxoQIQXNgOCBNyoXz_7XP4Vm7pIB1Lp35d67BbC4iSlrrcJoN1ZHCCI40
(1, id: "v4", ip: 65.108.42.3, secp256k1: 0x02105CD80E081372A17CFFED73F8566EE9201D4BA77E5DEBB05B0B889296BADC26, udp: 9101)
```
The record looks correct.

**Comment by jakubgs** [comment]
Apparently there's some RPC calls to list routing tables for protocols:
```
admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % ./rpc.sh discv5_routingTableInfo
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "localKey": "0x9c245a7865a2dbeea5e5d3e8c2f399122f95e47c78e4e0e774925ee2676494e6",
    "buckets": [
      [
        "0xd0036c40e5a44e220df97f39acd948407f97b58090cb4b42a59138512874dcc2",
        "0x4f42329a2f4aebf4e488b4daa639f5bd03230865e4f5b4a232234618025b0ba8",
        "0x9c0602032a3a273bd2b5745dac0defaa14a3b2d5059eeb8c761e0f1ad635490a"
      ]
    ]
  }
}

admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % ./rpc.sh portal_state_routingTableInfo                                    
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "localKey": "0x9c245a7865a2dbeea5e5d3e8c2f399122f95e47c78e4e0e774925ee2676494e6",
    "buckets": [
      [
        "0x4f42329a2f4aebf4e488b4daa639f5bd03230865e4f5b4a232234618025b0ba8",
        "0x9c0602032a3a273bd2b5745dac0defaa14a3b2d5059eeb8c761e0f1ad635490a",
        "0xd0036c40e5a44e220df97f39acd948407f97b58090cb4b42a59138512874dcc2"
      ]
    ]
  }
}

admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % ./rpc.sh portal_history_routingTableInfo
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "localKey": "0x9c245a7865a2dbeea5e5d3e8c2f399122f95e47c78e4e0e774925ee2676494e6",
    "buckets": [
      [
        "0x9c0602032a3a273bd2b5745dac0defaa14a3b2d5059eeb8c761e0f1ad635490a",
        "0x4f42329a2f4aebf4e488b4daa639f5bd03230865e4f5b4a232234618025b0ba8",
        "0xd0036c40e5a44e220df97f39acd948407f97b58090cb4b42a59138512874dcc2"
      ]
    ]
  }
}

```

**Comment by jakubgs** [comment]
Apparently `Bootstrap node could not be added` errors are related to other protocols, and don't mean the peers was not added.

**Comment by jakubgs** [comment]
I started running Ansible for other nodes, and it looks like they start appearing in the routing table:
```
admin@metal-01.he-eu-hel1.nimbus.fluffy:/data/nimbus-fluffy-mainnet-master-01 % ./rpc.sh discv5_routingTableInfo
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "localKey": "0x9c245a7865a2dbeea5e5d3e8c2f399122f95e47c78e4e0e774925ee2676494e6",
    "buckets": [
      [
        "0x4586b2807dbdc74a487b8b506c5446b015ebffcb47c7e4418e0ede80eb13870a",
        "0x207fab4efc0a18231e91cc67b495480ad247d6bf809e69c20a448234583e69e7",
        "0xd0036c40e5a44e220df97f39acd948407f97b58090cb4b42a59138512874dcc2",
        "0x4f42329a2f4aebf4e488b4daa639f5bd03230865e4f5b4a232234618025b0ba8",
        "0x9464e792a5fcef33f027bed8d727422863f7eb185e3a2444358d5275527ce11d",
        "0x9c0602032a3a273bd2b5745dac0defaa14a3b2d5059eeb8c761e0f1ad635490a",
        "0x85da4b261c45202e60c977da7daef7a7670d059c26bb44f09e86e852ebaf3f66"
      ]
    ]
  }
}
```
So it appears to work.

**Comment by jakubgs** [comment]
I configured the 4 bootstrap nodes statically for now: https://github.com/status-im/infra-nimbus/commit/3266a65a
