### ISSUE TITLE
Make use of ERA files support to reduce disk usage

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#98]
The support for new ERA files has been merged recently together with some docs:

* https://github.com/status-im/nimbus-eth2/pull/3605
* https://github.com/status-im/nimbus-eth2/pull/3394

For more info no those the docs are available at:
https://github.com/status-im/nimbus-eth2/blob/unstable/docs/e2store.md#era-files

In theory those files should reduce the disk usage of Nimbus nodes, which is becoming a problem, especially on mainnet:
```
admin@metal-02.he-eu-hel1.nimbus.mainnet:~ % sudo du -hsc /data/*
46G	/data/beacon-node-mainnet-stable-01
46G	/data/beacon-node-mainnet-stable-02
46G	/data/beacon-node-mainnet-testing-01
46G	/data/beacon-node-mainnet-testing-02
46G	/data/beacon-node-mainnet-unstable-01
46G	/data/beacon-node-mainnet-unstable-02
272G	total
admin@metal-02.he-eu-hel1.nimbus.mainnet:~ % df -h /             
Filesystem      Size  Used Avail Use% Mounted on
/dev/md2        436G  339G   75G  82% /
```

**Comment by arnetheduck** [comment]
> In theory we could do that at every node start/restart using [ExecStartPre](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=).

this is possible - in such a reality, each server should probably have one instance that is not wiped and instead is used as checkpoint sync source and era db source - all other instances would sync from here.

> Although that wouldn't give us the benefit of reclaiming space unless the node DB was also cleared.

checkpoint sync requires wiping the database first

**Comment by jakubgs** [comment]
I started the process of creating the ERA file on `metal-01.he-eu-hel1.nimbus.mainnet` from `beacon-node-mainnet-stable-02`:
```
admin@metal-01.he-eu-hel1.nimbus.mainnet:/data/beacon-node-mainnet-stable-02/era % sudo -u nimbus ../repo/build/ncli_db exportEra --db=$PWD/../data/shared_mainnet_0/db                                                                                                 
Initializing block pool...
TRC 2022-05-23 15:40:43.125+00:00 state_transition: processing block, signature passed topics="chaindag" tid=3307675 file=state_transition.nim:220 signature=8d95e178 blockRoot=3c632c3b
...
```
It started creating a lot of `era` files in the current directory:
```
admin@metal-01.he-eu-hel1.nimbus.mainnet:/data/beacon-node-mainnet-stable-02 % ls -l era | head 
total 3092096
-rw-r--r-- 1 nimbus staff  1810141 May 23 15:43 mainnet-00000-4b363db9.era
-rw-r--r-- 1 nimbus staff 18580262 May 23 15:43 mainnet-00001-40cf2f3c.era
-rw-r--r-- 1 nimbus staff 19565485 May 23 15:43 mainnet-00002-74a3850f.era
-rw-r--r-- 1 nimbus staff 18660406 May 23 15:43 mainnet-00003-76b05bfe.era
-rw-r--r-- 1 nimbus staff 20093454 May 23 15:43 mainnet-00004-f82d21ce.era
-rw-r--r-- 1 nimbus staff 19983422 May 23 15:43 mainnet-00005-4ec633af.era
-rw-r--r-- 1 nimbus staff 20641097 May 23 15:43 mainnet-00006-eef40204.era
-rw-r--r-- 1 nimbus staff 21459536 May 23 15:43 mainnet-00007-ce8f6ccd.era
-rw-r--r-- 1 nimbus staff 22035110 May 23 15:43 mainnet-00008-f0d27f1e.era
```
Which matches what the docs say:

>`.era` file names follow a simple convention: `<config-name>-<era-number>-<era-count>-<short-historical-root>.era`

https://github.com/status-im/nimbus-eth2/blob/unstable/docs/e2store.md#era-files

Would be nice if it has an `--our-dir` flag, but ah well.

**Comment by jakubgs** [comment]
So far so good. I left `beacon-node-mainnet-stable-01` as fully synced:
```
admin@metal-01.he-eu-hel1.nimbus.mainnet:~ % sudo du -hsc /data/*
60G	/data/beacon-node-mainnet-stable-01
3.5G	/data/beacon-node-mainnet-stable-02
3.3G	/data/beacon-node-mainnet-testing-01
3.3G	/data/beacon-node-mainnet-testing-02
3.3G	/data/beacon-node-mainnet-unstable-01
3.3G	/data/beacon-node-mainnet-unstable-02
48G	/data/era
124G	total
```
The nodes appear to be working:
```
admin@metal-01.he-eu-hel1.nimbus.mainnet:~ % for PORT in {9200..9205}; do c 0:$PORT/metrics | grep '^beacon_.*slot '; done                     
beacon_head_slot 3875116.0
beacon_slot 3875116.0
beacon_head_slot 3875116.0
beacon_slot 3875116.0
beacon_head_slot 3875116.0
beacon_slot 3875116.0
beacon_head_slot 3875116.0
beacon_slot 3875116.0
beacon_head_slot 3875116.0
beacon_slot 3875116.0
beacon_head_slot 3875116.0
beacon_slot 3875116.0
```

**Comment by jakubgs** [comment]
I'm going to leave this host as is for a day or two. Lets see how well that works.

The question is how much we want to automate this process. The bare minimum would look something like this:

* Ansible role managing a timer that can be enabled/disabled for creating and updating the `era` directory.
* Option in the `infra-role-beacon-node-*` Ansible role for spcifying and symlinking the `era` directory.
* Improved `sync.sh` script which also has option to stop the service, purge the db, sync, and restart.
* Optionally we could also include runnign of the `sync.sh` script using the `ExecStartPre` systemd option.

I don't know how permanent or prevalent this kind of setup will become, so I don't want to overdo it at first.

**Comment by jakubgs** [comment]
I've deployed the ERA file fix:

* https://github.com/status-im/nimbus-eth2/pull/3675

```
admin@metal-01.he-eu-hel1.nimbus.mainnet:~ % s list-units 'beacon-node-*'
  UNIT                                    LOAD   ACTIVE SUB     DESCRIPTION                                     
  beacon-node-mainnet-stable-01.service   loaded active running Nimbus Beacon Node on mainnet network (stable)  
  beacon-node-mainnet-stable-02.service   loaded active running Nimbus Beacon Node on mainnet network (stable)  
  beacon-node-mainnet-testing-01.service  loaded active running Nimbus Beacon Node on mainnet network (testing) 
  beacon-node-mainnet-testing-02.service  loaded active running Nimbus Beacon Node on mainnet network (testing) 
  beacon-node-mainnet-unstable-01.service loaded active running Nimbus Beacon Node on mainnet network (unstable)
  beacon-node-mainnet-unstable-02.service loaded active running Nimbus Beacon Node on mainnet network (unstable)
```
So far so good.

**Comment by jakubgs** [comment]
I encountered a new issue when using `ncli_db` to create a new ERA store on `metal-02.he-eu-hel1.nimbus.mainnet`:
```
INF 2022-06-02 10:39:35.787+00:00 Block DAG initialized                      tid=3520201 file=blockchain_dag.nim:924 head=c22aed38:3945195 finalizedHead=ecbaff07:3945120 tail=2c81f769:3807680 backfill="(0, \"00000000\")" loadDur=4ms908us777ns summariesDur=616ms263us597ns finalizedDur=3ms148us183ns frontfillDur=40ns keysDur=28us260ns
Writing mainnet-00000-4b363db9.era
DBG 2022-06-02 10:39:35.858+00:00 UpdateStateData cache miss                 topics="chaindag" tid=3520201 file=blockchain_dag.nim:1206 current=c22aed38:3945195 target=4d611d5b:0
TRC 2022-06-02 10:39:35.934+00:00 State advanced                             topics="chaindag" tid=3520201 file=blockchain_dag.nim:1309 blocks=0 slots=0 current=c22aed38:3945195 ancestor=4d611d5b:0 target=4d611d5b:0 ancestorStateRoot=7e76880e targetStateRoot=7e76880e found=false assignDur=75ms877us62ns replayDur=8us990ns
Writing mainnet-00001-40cf2f3c.era
TRC 2022-06-02 10:39:35.947+00:00 getBlockRange entered                      topics="chaindag" tid=3520201 file=blockchain_dag.nim:1071 head=c22aed38 requestedCount=8192 startSlot=0 skipStep=1 headSlot=3945195
DBG 2022-06-02 10:39:36.174+00:00 UpdateStateData cache miss                 topics="chaindag" tid=3520201 file=blockchain_dag.nim:1206 current=4d611d5b:0 target=a7d379a9:8192
NOT 2022-06-02 10:39:36.199+00:00 Request for pruned historical state        topics="chaindag" tid=3520201 file=blockchain_dag.nim:1238 request=a7d379a9:8192 tail=2c81f769:3807680 cur=6ecdaa08:6143
/data/beacon-node-mainnet-stable-01/repo/ncli/ncli_db.nim(1051) ncli_db
/data/beacon-node-mainnet-stable-01/repo/ncli/ncli_db.nim(521) cmdExportEra
/data/beacon-node-mainnet-stable-01/repo/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(22) raiseAssert
/data/beacon-node-mainnet-stable-01/repo/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: withUpdatedState failed [AssertionError]
```
Have you seen this @arnetheduck ?

**Comment by jakubgs** [comment]
I have switched all unstabled nodes to using `/data/era` folder generated from the first `stable` node on each host:
```
 > a nimbus-mainnet-metal --become -a 'du -hsc /data/*unstable*'
metal-01.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
5.1G	/data/beacon-node-mainnet-unstable-01
5.0G	/data/beacon-node-mainnet-unstable-02
11G	total
metal-02.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
5.0G	/data/beacon-node-mainnet-unstable-01
4.8G	/data/beacon-node-mainnet-unstable-02
9.8G	total
metal-03.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
4.3G	/data/beacon-node-mainnet-unstable-01
4.3G	/data/beacon-node-mainnet-unstable-02
8.5G	total
metal-04.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
4.3G	/data/beacon-node-mainnet-unstable-01
4.3G	/data/beacon-node-mainnet-unstable-02
8.5G	total
metal-05.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
51G	/data/beacon-node-mainnet-unstable-01
52G	/data/beacon-node-mainnet-unstable-02
103G	total
metal-06.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
3.5G	/data/beacon-node-mainnet-unstable-01
3.4G	/data/beacon-node-mainnet-unstable-02
6.9G	total
```
But on `metal-05.he-eu-hel1.nimbus.mainnet` I'm unable to create the ERA files because of the error above.

**Comment by arnetheduck** [comment]
> But on metal-05.he-eu-hel1.nimbus.mainnet I'm unable to create the ERA files because of the error above.

Checkpoint-synced nodes cannot create era files unless they run checkpoint sync with `--reindex`

**Comment by jakubgs** [comment]
I synced `stable-01` on `metal-05` from scratch and then created ERA files from it, works:
```
 > a metal-05.he-eu-hel1.nimbus.mainnet --become -a 'du -hsc /data/*unstable*'
metal-05.he-eu-hel1.nimbus.mainnet | CHANGED | rc=0 >>
8.4G	/data/beacon-node-mainnet-unstable-01
8.4G	/data/beacon-node-mainnet-unstable-02
17G	total
```

**Comment by jakubgs** [comment]
I've deployed a `nimbus-era-files-update` timer:
```
 > systemctl -o cat status nimbus-era-files-update
● nimbus-era-files-update.service - Update Nimbus beacon node ERA files
     Loaded: loaded (/etc/systemd/system/nimbus-era-files-update.service; static; vendor preset: enabled)
     Active: inactive (dead) since Wed 2022-07-13 20:22:16 UTC; 2h 31min ago
TriggeredBy: ● nimbus-era-files-update.timer
       Docs: https://github.com/status-im/infra-role-systemd-timer
    Process: 153635 ExecStart=/data/beacon-node-mainnet-stable-01/repo/build/ncli_db exportEra --db=/data/beacon-node-mainnet-stable-01/data/shared_mainnet_0/db (code=exited, status=0/SUCCESS)
   Main PID: 153635 (code=exited, status=0/SUCCESS)

Written all complete eras
All time are ms
     Average,       StdDev,          Min,          Max,      Samples,         Test
     565.673,       41.529,      486.430,      635.203,           45, tState
    1107.374,      147.118,      685.914,     1293.401,           45, tBlocks
nimbus-era-files-update.service: Succeeded.
Finished Update Nimbus beacon node ERA files.
```
It will run weekly with a random delay.

Changes:

- https://github.com/status-im/infra-nimbus/commit/00cfcf56 - nimbus-era-files: role for ERA generating timer
- https://github.com/status-im/infra-nimbus/commit/3cc72b68 - nimbus.mainnet: deploy nimbus-era-files to metal hosts

**Comment by jakubgs** [comment]
I've fixed the beacon node data folder path to not include the pointless `shared_{network}_0` subfolder:

- https://github.com/status-im/infra-role-beacon-node-linux/commit/f4259bdf - drop pointless shared_ subfolder from data path
- https://github.com/status-im/infra-role-beacon-node-macos/commit/5dee20ae - drop pointless shared_ subfolder from data path
- https://github.com/status-im/infra-role-beacon-node-windows/commit/846c428b - drop pointless shared_ subfolder from data path
- https://github.com/status-im/infra-nimbus/commit/57ec2fd9 - requirements: bump beacon node to use new data path

Now the folder structure is simpler, and we avoid extra confusing Ansible variables.

**Comment by jakubgs** [comment]
Configured symlinking `/data/era` for Mainnet nodes:

- https://github.com/status-im/infra-role-beacon-node-linux/commit/9ae76b49 - config: support symlinking ERA files directory

But Jacek also implemented a `--era-dir` flag, so we can use that once it's released:

- https://github.com/status-im/nimbus-eth2/pull/3895

**Comment by jakubgs** [comment]
Deployed resync jobs to `metal-01.he-eu-hel1.nimbus.mainnet` for even index nodes:

- https://github.com/status-im/infra-nimbus/commit/1ffc159f - use idx instead of port_offset loop_var name
- https://github.com/status-im/infra-nimbus/commit/e3c203c8 - nimbus.mainnet: enable purging DB for even nodes

https://github.com/status-im/infra-nimbus/blob/e3c203c81544aa95e38e20bf54728675559aa428/ansible/group_vars/nimbus.mainnet.yml#L33-L36

**Comment by jakubgs** [comment]
Had to fix how we stop and start the service in the `resync` timer:

- https://github.com/status-im/infra-role-systemd-timer/commit/d29da37f - support Conflicts with systemd_timer_unit_conflicts
- https://github.com/status-im/infra-role-systemd-timer/commit/0cc94695 - support ExecStopPost with systemd_timer_exec_start_post
- https://github.com/status-im/infra-role-beacon-node-linux/commit/8b0a4d47 - rsync: run as root to stop and start the service

Used `Conflicts` and `ExecStopPost` and uses `root` user so it works.

**Comment by jakubgs** [comment]
Something seems to be broken, because the current resyncs seem to ignore the `era` folder:
```
admin@metal-05.he-eu-hel1.nimbus.mainnet:~ % sudo du -hsc /data/*
40G	/data/beacon-node-mainnet-libp2p-01
74G	/data/beacon-node-mainnet-stable-01
41G	/data/beacon-node-mainnet-stable-02
50G	/data/beacon-node-mainnet-testing-01
51G	/data/beacon-node-mainnet-testing-02
41G	/data/beacon-node-mainnet-unstable-01
41G	/data/beacon-node-mainnet-unstable-02
59G	/data/era
393G	total

admin@metal-05.he-eu-hel1.nimbus.mainnet:~ % df -h /data
Filesystem      Size  Used Avail Use% Mounted on
/dev/md2        437G  412G  2.9G 100% /
```
Something changed recently and the `era` symlink in the data folder seems to be ignored @arnetheduck:
```
admin@metal-05.he-eu-hel1.nimbus.mainnet:~ % sudo ls -l /data/beacon-node-mainnet-unstable-02/data/era
lrwxrwxrwx 1 root root 9 Jun  7 12:13 /data/beacon-node-mainnet-unstable-02/data/era -> /data/era

admin@metal-05.he-eu-hel1.nimbus.mainnet:~ % sudo ls -l /data/beacon-node-mainnet-unstable-02/data/era/ | head
total 61174508
-rw-r--r-- 1 nimbus staff   1810141 Jun  7 11:47 mainnet-00000-4b363db9.era
-rw-r--r-- 1 nimbus staff  18580262 Jun  7 11:47 mainnet-00001-40cf2f3c.era
-rw-r--r-- 1 nimbus staff  19565485 Jun  7 11:47 mainnet-00002-74a3850f.era
-rw-r--r-- 1 nimbus staff  18660406 Jun  7 11:47 mainnet-00003-76b05bfe.era
-rw-r--r-- 1 nimbus staff  20093454 Jun  7 11:47 mainnet-00004-f82d21ce.era
-rw-r--r-- 1 nimbus staff  19983422 Jun  7 11:47 mainnet-00005-4ec633af.era
-rw-r--r-- 1 nimbus staff  20641097 Jun  7 11:47 mainnet-00006-eef40204.era
-rw-r--r-- 1 nimbus staff  21459536 Jun  7 11:47 mainnet-00007-ce8f6ccd.era
-rw-r--r-- 1 nimbus staff  22035110 Jun  7 11:47 mainnet-00008-f0d27f1e.era
```

**Comment by jakubgs** [comment]
I think the issue might have been caused by this PR:

* https://github.com/status-im/nimbus-eth2/pull/3895/files

But there is a default set in that PR:
```nim
func eraDir*(config: BeaconNodeConf): string =
  # The era directory should be shared between networks of the same type..
  string config.eraDirFlag.get(InputDir(config.dataDir / "era"))
```
So not sure what's wrong.

**Comment by jakubgs** [comment]
Oh for fuck's sake. This is the cause of the ERA folder not taking effect:
```
admin@metal-03.he-eu-hel1.nimbus.mainnet:~ % grep '^SERVICE_DATA_PATH' /data/beacon-node-mainnet-unstable-01/sync.sh
SERVICE_DATA_PATH="${SERVICE_PATH}/data/shared_${NETWORK_NAME}_0/"
```
I forgot to remove the `shared_*` subfolder from the `sync.sh` script:
https://github.com/status-im/infra-role-beacon-node-linux/blob/89a6a9a3/templates/scripts/sync.sh.j2#L9
So it was not creating a DB that would then be used by the node.

**Comment by jakubgs** [comment]
I've added the explicit use of `--era-dir` flag and fixed the DB folder path:

- https://github.com/status-im/infra-role-beacon-node-linux/commit/18884c90 - sync.sh: drop shared_ subfolder causing issues
- https://github.com/status-im/infra-role-beacon-node-linux/commit/2a7aca74 - service: use --era-dir flag explicitly
- https://github.com/status-im/infra-role-beacon-node-linux/commit/45269486 - resync: don't use unit conflicts to stop service
- https://github.com/status-im/infra-role-beacon-node-linux/commit/5f4cb0d3 - config: lower groups permissions on directories

It appears everything is working again:
```
admin@metal-06.he-eu-hel1.nimbus.mainnet:~ % sudo du -hsc /data/*
15G	/data/beacon-node-mainnet-libp2p-01
63G	/data/beacon-node-mainnet-stable-01
29G	/data/beacon-node-mainnet-stable-02
5.1G	/data/beacon-node-mainnet-testing-01
5.1G	/data/beacon-node-mainnet-testing-02
5.5G	/data/beacon-node-mainnet-unstable-01
5.5G	/data/beacon-node-mainnet-unstable-02
60G	/data/era
185G	total
admin@metal-06.he-eu-hel1.nimbus.mainnet:~ % for port in $(seq 9300 9305); do c 0:$port/eth/v1/node/syncing | jq -c; done
{"data":{"head_slot":"4578935","sync_distance":"0","is_syncing":false}}
{"data":{"head_slot":"2233084","sync_distance":"2345851","is_syncing":true}}
{"data":{"head_slot":"4578935","sync_distance":"0","is_syncing":false}}
{"data":{"head_slot":"4578935","sync_distance":"0","is_syncing":false}}
{"data":{"head_slot":"4578935","sync_distance":"0","is_syncing":false}}
{"data":{"head_slot":"4578935","sync_distance":"0","is_syncing":false}}
```
