### ISSUE TITLE
Mass Prater validator slashing on 2022/05/26

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#99]
Most happened 4 days ago:

![image](https://user-images.githubusercontent.com/2212681/170979601-4d314428-7c01-473f-a904-2dd1fe415d77.png)

Which matches with a change I made 4 days ago to fetch current state of `nimbus-private` for Windows host:

* https://github.com/status-im/infra-role-dist-validators/commit/99a6a191c2e16206bb15c1c461411b85caae015b

**Comment by jakubgs** [comment]
Unfortunately we don't have logs older than 2 days because the Nimbus ES cluster failed due to a host that had both drives fail:
```
admin@store-01.he-eu-hel1.logs.nimbus:~ % sudo dmesg
sudo: unable to execute /usr/bin/dmesg: Input/output error

admin@store-01.he-eu-hel1.logs.nimbus:~ % sudo reboot
Failed to open initctl fifo: No such device or address
Failed to talk to init daemon.
```
The host was powered down and Hetzner support found out that both drives were degraded:
```
Both of the drives have become unusable, second particularly has disappeared altogether.
```
So that's shitty.

**Comment by jakubgs** [comment]
If I look at a specific slashed validator, for example:

https://prater.beaconcha.in/validator/95376d91ae379b463f6c91d256c3464c0fdb59407501e8ac77fde9c03daa639d05533c1cce55fc15f2e1a9f7af742b27

I can find it only on one host:
```
 > ansible nimbus.prater --become -a 'find /data/beacon-node-*/data/shared_prater_0/secrets -name 0x95376d91ae379b463f6c91d256c3464c0fdb59407501e8ac77fde9c03daa639d05533c1cce55fc15f2e1a9f7af742b27'
```
```
metal-06.he-eu-hel1.nimbus.prater | CHANGED | rc=0 >>
/data/beacon-node-prater-stable/data/shared_prater_0/secrets/0x95376d91ae379b463f6c91d256c3464c0fdb59407501e8ac77fde9c03daa639d05533c1cce55fc15f2e1a9f7af742b27
```

**Comment by jakubgs** [comment]
Another example I checked was:

https://prater.beaconcha.in/validator/0x9645a2961622e5347ef78cdee9798fbd36c4ddc3710eb51900746f52c4a77a672771aae3b5230d80478165f1451f2090

Which is also found on `metal-06`:
```
metal-06.he-eu-hel1.nimbus.prater | CHANGED | rc=0 >>
/data/beacon-node-prater-stable/data/shared_prater_0/secrets/0x9645a2961622e5347ef78cdee9798fbd36c4ddc3710eb51900746f52c4a77a672771aae3b5230d80478165f1451f2090
```
And I can't find it anywhere else.

**Comment by jakubgs** [comment]
One possibility is that despite the layout on the host volumes being correct(without duplicates) some of the nodes might have not been restarted and were running with an old validator layout that caused this. But I can't really confirm this.

**Comment by jakubgs** [comment]
The two most recent slashings:

* https://prater.beaconcha.in/validator/175835
* https://prater.beaconcha.in/validator/181632

Were on `macos-01` host running on `unstable` branch:
```
admin@macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus % sudo ls -l beacon-node-prater-unstable/data/shared_prater_0/secrets/0x91120da50b6b572525f5beb019028774498ad1dec9bc5b0dccd5c974944d9a3de0569689d74d017c9f620a0d8825f978
-rw-------  1 nimbus  staff  64 Feb 17 19:00 beacon-node-prater-unstable/data/shared_prater_0/secrets/0x91120da50b6b572525f5beb019028774498ad1dec9bc5b0dccd5c974944d9a3de0569689d74d017c9f620a0d8825f978
admin@macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus % sudo ls -l beacon-node-prater-unstable/data/shared_prater_0/secrets/0x90b7d4e14d0226fce001c2963d4b00c0c14395baf383b2d0ab7d0be37a4e73bb13faca6cbc1e3e07a839ad247ae7f5c1
-rw-------  1 nimbus  staff  64 Feb 17 19:00 beacon-node-prater-unstable/data/shared_prater_0/secrets/0x90b7d4e14d0226fce001c2963d4b00c0c14395baf383b2d0ab7d0be37a4e73bb13faca6cbc1e3e07a839ad247ae7f5c1
```

**Comment by jakubgs** [comment]
Here's some logs from `macos-01` for: https://prater.beaconcha.in/block/3116763#attester-slashings
```
admin@macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-unstable/logs % grep 3116763 service.log | tail -n20
{"lvl":"DBG","ts":"2022-05-30 12:12:55.914+01:00","msg":"Peer status","topics":"sync","peer":"16U*2qGVKy","statusMsg":{"forkDigest":"0x82f4a72b","finalizedRoot":"d09d98ee","finalizedEpoch":97396,"headRoot":"bee09dc0","headSlot":3116763}}
{"lvl":"INF","ts":"2022-05-30 12:12:56.172+01:00","msg":"Slot end","topics":"beacnde","slot":3116764,"nextActionWait":"3s827ms771us0ns","nextAttestationSlot":3116765,"nextProposalSlot":-1,"head":"bee09dc0:3116763"}
{"lvl":"DBG","ts":"2022-05-30 12:12:56.271+01:00","msg":"Peer status","topics":"sync","peer":"16U*e6jtgv","statusMsg":{"forkDigest":"0x82f4a72b","finalizedRoot":"d09d98ee","finalizedEpoch":97396,"headRoot":"bee09dc0","headSlot":3116763}}
{"lvl":"DBG","ts":"2022-05-30 12:12:57.144+01:00","msg":"Peer status","topics":"sync","peer":"16U*F94EbQ","statusMsg":{"forkDigest":"0x82f4a72b","finalizedRoot":"d09d98ee","finalizedEpoch":97396,"headRoot":"bee09dc0","headSlot":3116763}}
{"lvl":"DBG","ts":"2022-05-30 12:12:57.178+01:00","msg":"Peer status","topics":"sync","peer":"16U*F94EbQ","statusMsg":{"forkDigest":"0x82f4a72b","finalizedRoot":"d09d98ee","finalizedEpoch":97396,"headRoot":"bee09dc0","headSlot":3116763}}
{"lvl":"DBG","ts":"2022-05-30 12:12:57.610+01:00","msg":"Current syncing state","topics":"syncman","workers_map":"ssssssssss","sleeping_workers_count":10,"waiting_workers_count":0,"pending_workers_count":0,"wall_head_slot":3116764,"local_head_slot":3116763,"pause_time":"0ns","avg_sync_speed":0.0,"ins_sync_speed":0.0,"sync_ident":"main","direction":"forward"}
{"lvl":"DBG","ts":"2022-05-30 12:12:57.610+01:00","msg":"Synchronization loop sleeping","topics":"syncman","wall_head_slot":3116764,"local_head_slot":3116763,"difference":1,"max_head_age":32,"sync_ident":"main","direction":"forward"}
{"lvl":"DBG","ts":"2022-05-30 12:12:59.452+01:00","msg":"Attester slashing received","attesterSlashing":{"attestation_1":{"attestating_indices":[3933,12052,13360,14321,14585,15543,19029,21223,21330,21394,22717,22818,28768,30263,30322,41691,42542,43013,43822,47266,47283,47728,49882,51242,52203,54303,58039,58329,60251,60954,61826,65895,67260,73752,75164,76894,81916,81982,84671,86876,87038,92130,93887,96904,99143,102790,103855,104276,106691,111362,118714,120905,122832,125957,127044,132047,132165,133241,133725,134153,134367,146142,150045,150989,153275,154307,158757,162662,163126,167329,167346,172496,173141,173524,179627,186192,196530,199508,200242,202098,207367,207908,211298,213923,220215,223750,225325,225499,230271,244764,245401,247611,247668,249400,250118,250819,251528,251861,253821,255637,266206,267640,269517,272790,281333,286147,286768,290224,295190,295219,302479,304082,306500,306685,311887,312086,314676,314973,316513,316550,318396,319594,323036],"data":{"slot":3116763,"index":6,"beacon_block_root":"bee09dc0","source":"97397:8bf9fde9","target":"97398:f4ec291b"},"signature":"8a9fd383"},"attestation_2":{"attestating_indices":[186192,309422],"data":{"slot":3116763,"index":6,"beacon_block_root":"0ca849bd","source":"97397:8bf9fde9","target":"97398:f4ec291b"},"signature":"845853f0"}}}
{"lvl":"WRN","ts":"2022-05-30 12:12:59.455+01:00","msg":"Attester slashing seen","topics":"val_mon","slot":3116763,"validator":"91044cd5","src":0}
{"lvl":"DBG","ts":"2022-05-30 12:12:59.611+01:00","msg":"Current syncing state","topics":"syncman","workers_map":"ssssssssss","sleeping_workers_count":10,"waiting_workers_count":0,"pending_workers_count":0,"wall_head_slot":3116764,"local_head_slot":3116763,"pause_time":"0ns","avg_sync_speed":0.0,"ins_sync_speed":0.0,"sync_ident":"main","direction":"forward"}
{"lvl":"DBG","ts":"2022-05-30 12:12:59.611+01:00","msg":"Synchronization loop sleeping","topics":"syncman","wall_head_slot":3116764,"local_head_slot":3116763,"difference":1,"max_head_age":32,"sync_ident":"main","direction":"forward"}
{"lvl":"INF","ts":"2022-05-30 12:13:00.001+01:00","msg":"Slot start","topics":"beacnde","slot":3116765,"epoch":97398,"sync":"synced","peers":201,"head":"bee09dc0:3116763","finalized":"97396:d09d98ee","delay":"1ms122us0ns"}
{"lvl":"DBG","ts":"2022-05-30 12:13:00.006+01:00","msg":"Waiting to send attestations","topics":"beacval","head":"bee09dc0:3116763","attestationCutoff":"3s993ms326us0ns"}
{"lvl":"DBG","ts":"2022-05-30 12:13:00.583+01:00","msg":"Peer status","topics":"sync","peer":"16U*ZWyoN8","statusMsg":{"forkDigest":"0x82f4a72b","finalizedRoot":"d09d98ee","finalizedEpoch":97396,"headRoot":"bee09dc0","headSlot":3116763}}
{"lvl":"DBG","ts":"2022-05-30 12:13:00.862+01:00","msg":"Updated head block","topics":"chaindag","stateRoot":"4fd255c9","justified":"97397:8bf9fde9","finalized":"97396:d09d98ee","newHead":"388dc1ac:3116765","lastHead":"bee09dc0:3116763"}
{"lvl":"DBG","ts":"2022-05-30 12:13:00.864+01:00","msg":"Got block, waiting to send attestations","topics":"beacval","head":"bee09dc0:3116763","afterBlockCutoff":"2s0ns"}
{"lvl":"DBG","ts":"2022-05-30 12:13:02.111+01:00","msg":"Attester slashing received","attesterSlashing":{"attestation_1":{"attestating_indices":[167349,175882,312986],"data":{"slot":3116763,"index":25,"beacon_block_root":"0ca849bd","source":"97397:8bf9fde9","target":"97398:f4ec291b"},"signature":"91fbfa15"},"attestation_2":{"attestating_indices":[5835,9192,11988,13427,15362,19540,22104,30651,41411,42156,43339,43795,44020,51220,51876,53062,55798,57797,58174,60320,64050,70051,71814,75441,75578,77001,77002,80053,80291,80473,83334,85714,86533,89358,89535,90121,91350,96404,97140,98498,99877,102323,107279,108829,110161,112944,115003,118426,119819,121598,122996,123264,123417,125332,129726,132213,137238,140942,141953,143255,148187,149572,149793,151778,154240,156877,159741,162749,162765,166338,167349,168505,171995,172996,174031,174195,175882,177818,193786,196173,204726,208153,208384,214976,217178,225934,226856,228661,242692,243766,249368,251201,252238,262088,264134,264608,265310,266793,267150,269334,270195,270410,273484,274222,276185,285548,290171,290676,291625,295719,301619,313094,316739,318049,318800],"data":{"slot":3116763,"index":25,"beacon_block_root":"bee09dc0","source":"97397:8bf9fde9","target":"97398:f4ec291b"},"signature":"a5086254"}}}
{"lvl":"WRN","ts":"2022-05-30 12:13:02.114+01:00","msg":"Attester slashing seen","topics":"val_mon","slot":3116763,"validator":"91367dbe","src":0}
{"lvl":"WRN","ts":"2022-05-30 12:13:02.114+01:00","msg":"Attester slashing seen","topics":"val_mon","slot":3116763,"validator":"916829ba","src":0}
{"lvl":"DBG","ts":"2022-05-30 12:13:03.975+01:00","msg":"LC optimistic update received","optimistic_update":{"attested":{"slot":3116763,"proposer_index":137987,"parent_root":"70422e7b","state_root":"f154373f"},"num_active_participants":369,"signature_slot":3116765}}
```

**Comment by jakubgs** [comment]
Here's an example of a validator that got slashed recently: https://prater.beaconcha.in/validator/179933
```
admin@metal-05.he-eu-hel1.nimbus.prater:~ % sudo find /data/beacon-node-prater-* -name 0x94fada38b72d51c4da724028431b11754dad83eeae0566a98fb66428547986ad9da3a39add71d118f0a1b1bb9cbc6890                                                                                                                                    
/data/beacon-node-prater-unstable/data/shared_prater_0/secrets/0x94fada38b72d51c4da724028431b11754dad83eeae0566a98fb66428547986ad9da3a39add71d118f0a1b1bb9cbc6890
/data/beacon-node-prater-unstable/data/shared_prater_0/validators/0x94fada38b72d51c4da724028431b11754dad83eeae0566a98fb66428547986ad9da3a39add71d118f0a1b1bb9cbc6890
```
It exists on `unstable` node on `metal-05.he-eu-hel1.nimbus.prater` as far as I can tell.

**Comment by jakubgs** [comment]
One thing that comes to mind is a deployment accident when Zahary made these changes and added 10k validators to Prater:

* https://github.com/status-im/infra-nimbus/pull/95
* https://github.com/status-im/nimbus-private/commit/e963d195f3b7a315241a410e14984c7769da5279

https://github.com/status-im/infra-nimbus/blob/6eede4900c1e4ce90be78a18de3062667a223e79/ansible/group_vars/nimbus.prater.yml#L102-L106

Incorrectly I assumed initially the deployment is necessary only on `metal-06.he-eu-hel1.nimbus.prate`, and once I realized that I ran Ansible for the whole `nimbus.prater` fleet, and mentioned this to Zahary:

![image](https://user-images.githubusercontent.com/2212681/170987233-242ffd15-0240-4893-a31d-395386c31114.png)

This might be related.

**Comment by jakubgs** [comment]
I have created a full list of validators on all hosts and found out a few things. First of all, we're missing 2k validators:
```
 > wc -l allkeys  
48000 allkeys
```
It should be 50k, but there's a gap, and it can be seen here:
https://github.com/status-im/infra-nimbus/blob/b1545a66624de467e23fb073a6a7dea37c3e26c9/ansible/group_vars/nimbus.prater.yml#L62-L65
There is no `10000` to `12000` range defined, and this mistake was initially made here: https://github.com/status-im/infra-nimbus/commit/65304b6aaabac6a4a3caf12e0217cf31722279a4

**Comment by jakubgs** [comment]
And second thing I found is that there's 2000 validators overlapping:
```
 > sort pubkeys| uniq -c | grep '^ \+2' | wc -l
2000
```
Specifically, they are on `macos-01` and `windows-01`:
```
 > sort pubkeys| uniq -c | grep '^ \+2' | head -n2
      2 0x8f96780da331cb6bc8cc706d90f7b543f71015ff79378871d9f21c72acfeb4436a6274f9a7cca6df2ac42fb92b101146
      2 0x8f97b908265148df425466d62a52ce1f5478ab5b494a643136431b3183a09f03fb574cbadff31d4e4f60f0812c349b4e

 > sort pubkeys| uniq -c | grep '^ \+2' | tail -n2
      2 0x921d996acd5467cdd9d38d597b97f904ddefe8da935c6f1c6cd037497b835be9bc1db76ea8ec96438de9fbabdaef12fe
      2 0x921da3ecbe77fd1c9f38c64415e5a428da4afce2a1523ce8889c35f6a54f99a38ca7b4d9380d122fc3d85c0ffd455220
```
```
 > ag 0x8f96780da331cb6bc8cc706d90f7b543f71015ff79378871d9f21c72acfeb4436a6274f9a7cca6df2ac42fb92b101146
windows-01
982:windows-01.he-eu-hel1.nimbus.prater:C:/Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/secrets/0x8f96780da331cb6bc8cc706d90f7b543f71015ff79378871d9f21c72acfeb4436a6274f9a7cca6df2ac42fb92b101146

macos-01
4001:macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-unstable/data/shared_prater_0/secrets/0x8f96780da331cb6bc8cc706d90f7b543f71015ff79378871d9f21c72acfeb4436a6274f9a7cca6df2ac42fb92b101146

 > ag 0x8f97b908265148df425466d62a52ce1f5478ab5b494a643136431b3183a09f03fb574cbadff31d4e4f60f0812c349b4e
macos-01
4002:macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-unstable/data/shared_prater_0/secrets/0x8f97b908265148df425466d62a52ce1f5478ab5b494a643136431b3183a09f03fb574cbadff31d4e4f60f0812c349b4e

windows-01
986:windows-01.he-eu-hel1.nimbus.prater:C:/Users/nimbus/beacon-node-prater-stable/data/shared_prater_0/secrets/0x8f97b908265148df425466d62a52ce1f5478ab5b494a643136431b3183a09f03fb574cbadff31d4e4f60f0812c349b4e

 > ag 0x921d996acd5467cdd9d38d597b97f904ddefe8da935c6f1c6cd037497b835be9bc1db76ea8ec96438de9fbabdaef12fe
windows-01
3492:windows-01.he-eu-hel1.nimbus.prater:C:/Users/nimbus/beacon-node-prater-testing/data/shared_prater_0/secrets/0x921d996acd5467cdd9d38d597b97f904ddefe8da935c6f1c6cd037497b835be9bc1db76ea8ec96438de9fbabdaef12fe

macos-01
5999:macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-unstable/data/shared_prater_0/secrets/0x921d996acd5467cdd9d38d597b97f904ddefe8da935c6f1c6cd037497b835be9bc1db76ea8ec96438de9fbabdaef12fe

 > ag 0x921da3ecbe77fd1c9f38c64415e5a428da4afce2a1523ce8889c35f6a54f99a38ca7b4d9380d122fc3d85c0ffd455220
macos-01
6000:macos-01.ms-eu-dublin.nimbus.prater:/Users/nimbus/beacon-node-prater-unstable/data/shared_prater_0/secrets/0x921da3ecbe77fd1c9f38c64415e5a428da4afce2a1523ce8889c35f6a54f99a38ca7b4d9380d122fc3d85c0ffd455220

windows-01
3493:windows-01.he-eu-hel1.nimbus.prater:C:/Users/nimbus/beacon-node-prater-testing/data/shared_prater_0/secrets/0x921da3ecbe77fd1c9f38c64415e5a428da4afce2a1523ce8889c35f6a54f99a38ca7b4d9380d122fc3d85c0ffd455220
```

**Comment by jakubgs** [comment]
None of the duplicated validators were added in the change made by Zahary:
```
~/work/nimbus-private/prater_deposits/secrets master
 > g show --stat 12288508cdc9a716581f85aac00189a3b5f0e1bb | grep -f ~/pubkeys
```

**Comment by jakubgs** [comment]
I checked first 4 pages of recent validators slashed and all were from `macos-01` or `windows-01`:

![image](https://user-images.githubusercontent.com/2212681/171005106-2d778fac-f7ac-4d12-b67a-081036d639db.png)

https://prater.beaconcha.in/validators/slashings

**Comment by jakubgs** [comment]
I ran Ansible on `macos-01` and indeed the validator layout changed:
```
 > diff macos-01.new macos-01.old | wc -l
10762
```
So there was definitely an issue there, lets see `windows-01`.

**Comment by jakubgs** [comment]
I've ran Ansible for Windows and there was no change to the validator layout, so it seems like that was the source of the issue.

At least for the validators slashed on 26th of May. Since according to @Menduist there were:
```
13 slashes on the 6th
1 on the 7th
80 on th 8th
9 on the 10th
2 on the 13
3 on the 20
1300 on the 26
2 on the 28
600 today
```

**Comment by jakubgs** [comment]
It appears to me that the cause - while not clear - seems to stem from several issues:

* Incorrect validator layout created in https://github.com/status-im/infra-nimbus/commit/65304b6aaabac6a4a3caf12e0217cf31722279a4 and https://github.com/status-im/infra-nimbus/commit/65304b6aaabac6a4a3caf12e0217cf31722279a4 which was missing the `10000` to `12000` range
* Incorrect deployment order of new layout of 10k validators done in https://github.com/status-im/infra-nimbus/pull/95
* Update to Windows validators triggered by doppelganger detection and repo update in [`99a6a191`](https://github.com/status-im/infra-role-dist-validators/commit/99a6a191c2e16206bb15c1c461411b85caae015b)
* Simplified and rough process used by [`dist_validators.py`](https://github.com/status-im/infra-role-dist-validators/blob/master/files/dist_validators.py) which requires manual intervention when restarting nodes
* Need for manual stopping and restarting of nodes to avoid clashes due to partially changed layout across hosts
* Lack of validation of layout. No process for easily checking for overlaps.

The whole process of deploying validators using ranges and Ansible is extremely prone to error.
An optimal setup would probably have a central source of validators which keeps a map of validators and their respective nodes/hosts, and provides them based on some authenticated request.

**Comment by jakubgs** [comment]
For future reference, the investigation on discord started here:
https://discord.com/channels/613988663034118151/641680546191376384/980752179570831411

**Comment by jakubgs** [comment]
The full number of currently slashed validators is 2877:

![image](https://user-images.githubusercontent.com/2212681/171391861-6ecf91c9-4f7a-4f6b-b6da-a93de57a8266.png)

**Comment by jakubgs** [comment]
Here is a full list of slashed validators: https://gist.github.com/jakubgs/f23641900a2b7b3de476dcf193d7d78b

I've archived them in the `nimbus-private` repository: https://github.com/status-im/nimbus-private/pull/12

**Comment by Marudny** [comment]
> The whole process of deploying validators using ranges and Ansible is extremely prone to error.
> An optimal setup would probably have a central source of validators which keeps a map of validators and their respective nodes/hosts, and provides them based on some authenticated request.

I've been thinking for a while about that. It's feasible. I'm attaching mind-map with my thoughts
![Validators Deployment](https://user-images.githubusercontent.com/49659297/171423272-04d43d37-589c-4971-b575-c1e25820c5e7.png)

**Comment by jakubgs** [comment]
@Marudny well, it would be cool to have a proper solution, but at the same time, I don't know if we want to spend a large amount of time developing a complex automation for something that happens essentially once a month or even less frequently.

Such a piece of software, if it was to be separate as agent and server, would require quite a lot of functionality to work:

* Would need to be aware of the __defined layout__ of validators. Validator key mappings to host+node.
* Would need to be aware of the __current layout__ in effect on the hosts in order to avoid overlaps when deploying.
* Would need to make non-trivial decissions about which hosts to stop, deploy to, and start, and crucially, in what order.
* Would need to validate that the deployment works, as in, the validators were effectively attached or removed.

This would be quite complex as far as I can tell. Not sure if it's worth it considering we don't change layouts often.
It would make sense if we were trying to develop a solution that could be then used in production to manage validators, but if that's the case it would make more sense to make such a tool an integral part of `nimbus-eth2` that would make the node itself request validators to use at startup, rather than a hard to manage set of wrappers around filesystem changes and systemd.

What do you think @arnetheduck @zah?

**Comment by jakubgs** [comment]
I've closed both PRs trying to clear up the slashed validators as @arnetheduck said it's good thing we also cover that case.

* https://github.com/status-im/infra-nimbus/pull/102
* https://github.com/status-im/nimbus-private/pull/12

Since the  `validator_monitor_slashed` metrics doesn't get reset to 0 at startup we can use the `delta()` to alert.
